// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/ai_agent.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAIAgentGetChatHistory = "/api.rider.v1.AIAgent/GetChatHistory"
const OperationAIAgentGetFAQList = "/api.rider.v1.AIAgent/GetFAQList"
const OperationAIAgentGetSuggestedQuestions = "/api.rider.v1.AIAgent/GetSuggestedQuestions"
const OperationAIAgentRateService = "/api.rider.v1.AIAgent/RateService"
const OperationAIAgentSendMessage = "/api.rider.v1.AIAgent/SendMessage"

type AIAgentHTTPServer interface {
	// GetChatHistory 获取聊天历史
	GetChatHistory(context.Context, *AIAgentGetChatHistoryRequest) (*AIAgentGetChatHistoryReply, error)
	// GetFAQList 获取常见问题列表
	GetFAQList(context.Context, *AIAgentGetFAQListRequest) (*AIAgentGetFAQListReply, error)
	// GetSuggestedQuestions 获取智能推荐问题
	GetSuggestedQuestions(context.Context, *AIAgentGetSuggestedQuestionsRequest) (*AIAgentGetSuggestedQuestionsReply, error)
	// RateService 评价客服服务
	RateService(context.Context, *AIAgentRateServiceRequest) (*AIAgentRateServiceReply, error)
	// SendMessage 发送消息给AI客服
	SendMessage(context.Context, *AIAgentSendMessageRequest) (*AIAgentSendMessageReply, error)
}

func RegisterAIAgentHTTPServer(s *http.Server, srv AIAgentHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/ai-agent/send", _AIAgent_SendMessage0_HTTP_Handler(srv))
	r.GET("/rider/v1/ai-agent/history", _AIAgent_GetChatHistory0_HTTP_Handler(srv))
	r.GET("/rider/v1/ai-agent/faq", _AIAgent_GetFAQList0_HTTP_Handler(srv))
	r.POST("/rider/v1/ai-agent/rate", _AIAgent_RateService0_HTTP_Handler(srv))
	r.GET("/rider/v1/ai-agent/suggestions", _AIAgent_GetSuggestedQuestions0_HTTP_Handler(srv))
}

func _AIAgent_SendMessage0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AIAgentSendMessageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentSendMessage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SendMessage(ctx, req.(*AIAgentSendMessageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AIAgentSendMessageReply)
		return ctx.Result(200, reply)
	}
}

func _AIAgent_GetChatHistory0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AIAgentGetChatHistoryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentGetChatHistory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChatHistory(ctx, req.(*AIAgentGetChatHistoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AIAgentGetChatHistoryReply)
		return ctx.Result(200, reply)
	}
}

func _AIAgent_GetFAQList0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AIAgentGetFAQListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentGetFAQList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetFAQList(ctx, req.(*AIAgentGetFAQListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AIAgentGetFAQListReply)
		return ctx.Result(200, reply)
	}
}

func _AIAgent_RateService0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AIAgentRateServiceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentRateService)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RateService(ctx, req.(*AIAgentRateServiceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AIAgentRateServiceReply)
		return ctx.Result(200, reply)
	}
}

func _AIAgent_GetSuggestedQuestions0_HTTP_Handler(srv AIAgentHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AIAgentGetSuggestedQuestionsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAIAgentGetSuggestedQuestions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSuggestedQuestions(ctx, req.(*AIAgentGetSuggestedQuestionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AIAgentGetSuggestedQuestionsReply)
		return ctx.Result(200, reply)
	}
}

type AIAgentHTTPClient interface {
	// GetChatHistory 获取聊天历史
	GetChatHistory(ctx context.Context, req *AIAgentGetChatHistoryRequest, opts ...http.CallOption) (rsp *AIAgentGetChatHistoryReply, err error)
	// GetFAQList 获取常见问题列表
	GetFAQList(ctx context.Context, req *AIAgentGetFAQListRequest, opts ...http.CallOption) (rsp *AIAgentGetFAQListReply, err error)
	// GetSuggestedQuestions 获取智能推荐问题
	GetSuggestedQuestions(ctx context.Context, req *AIAgentGetSuggestedQuestionsRequest, opts ...http.CallOption) (rsp *AIAgentGetSuggestedQuestionsReply, err error)
	// RateService 评价客服服务
	RateService(ctx context.Context, req *AIAgentRateServiceRequest, opts ...http.CallOption) (rsp *AIAgentRateServiceReply, err error)
	// SendMessage 发送消息给AI客服
	SendMessage(ctx context.Context, req *AIAgentSendMessageRequest, opts ...http.CallOption) (rsp *AIAgentSendMessageReply, err error)
}

type AIAgentHTTPClientImpl struct {
	cc *http.Client
}

func NewAIAgentHTTPClient(client *http.Client) AIAgentHTTPClient {
	return &AIAgentHTTPClientImpl{client}
}

// GetChatHistory 获取聊天历史
func (c *AIAgentHTTPClientImpl) GetChatHistory(ctx context.Context, in *AIAgentGetChatHistoryRequest, opts ...http.CallOption) (*AIAgentGetChatHistoryReply, error) {
	var out AIAgentGetChatHistoryReply
	pattern := "/rider/v1/ai-agent/history"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIAgentGetChatHistory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetFAQList 获取常见问题列表
func (c *AIAgentHTTPClientImpl) GetFAQList(ctx context.Context, in *AIAgentGetFAQListRequest, opts ...http.CallOption) (*AIAgentGetFAQListReply, error) {
	var out AIAgentGetFAQListReply
	pattern := "/rider/v1/ai-agent/faq"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIAgentGetFAQList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSuggestedQuestions 获取智能推荐问题
func (c *AIAgentHTTPClientImpl) GetSuggestedQuestions(ctx context.Context, in *AIAgentGetSuggestedQuestionsRequest, opts ...http.CallOption) (*AIAgentGetSuggestedQuestionsReply, error) {
	var out AIAgentGetSuggestedQuestionsReply
	pattern := "/rider/v1/ai-agent/suggestions"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAIAgentGetSuggestedQuestions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RateService 评价客服服务
func (c *AIAgentHTTPClientImpl) RateService(ctx context.Context, in *AIAgentRateServiceRequest, opts ...http.CallOption) (*AIAgentRateServiceReply, error) {
	var out AIAgentRateServiceReply
	pattern := "/rider/v1/ai-agent/rate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIAgentRateService))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SendMessage 发送消息给AI客服
func (c *AIAgentHTTPClientImpl) SendMessage(ctx context.Context, in *AIAgentSendMessageRequest, opts ...http.CallOption) (*AIAgentSendMessageReply, error) {
	var out AIAgentSendMessageReply
	pattern := "/rider/v1/ai-agent/send"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAIAgentSendMessage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
