// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/ai_agent.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AIAgent_SendMessage_FullMethodName           = "/api.rider.v1.AIAgent/SendMessage"
	AIAgent_GetChatHistory_FullMethodName        = "/api.rider.v1.AIAgent/GetChatHistory"
	AIAgent_GetFAQList_FullMethodName            = "/api.rider.v1.AIAgent/GetFAQList"
	AIAgent_RateService_FullMethodName           = "/api.rider.v1.AIAgent/RateService"
	AIAgent_GetSuggestedQuestions_FullMethodName = "/api.rider.v1.AIAgent/GetSuggestedQuestions"
)

// AIAgentClient is the client API for AIAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AI智能体客服服务
type AIAgentClient interface {
	// 发送消息给AI客服
	SendMessage(ctx context.Context, in *AIAgentSendMessageRequest, opts ...grpc.CallOption) (*AIAgentSendMessageReply, error)
	// 获取聊天历史
	GetChatHistory(ctx context.Context, in *AIAgentGetChatHistoryRequest, opts ...grpc.CallOption) (*AIAgentGetChatHistoryReply, error)
	// 获取常见问题列表
	GetFAQList(ctx context.Context, in *AIAgentGetFAQListRequest, opts ...grpc.CallOption) (*AIAgentGetFAQListReply, error)
	// 评价客服服务
	RateService(ctx context.Context, in *AIAgentRateServiceRequest, opts ...grpc.CallOption) (*AIAgentRateServiceReply, error)
	// 获取智能推荐问题
	GetSuggestedQuestions(ctx context.Context, in *AIAgentGetSuggestedQuestionsRequest, opts ...grpc.CallOption) (*AIAgentGetSuggestedQuestionsReply, error)
}

type aIAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewAIAgentClient(cc grpc.ClientConnInterface) AIAgentClient {
	return &aIAgentClient{cc}
}

func (c *aIAgentClient) SendMessage(ctx context.Context, in *AIAgentSendMessageRequest, opts ...grpc.CallOption) (*AIAgentSendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIAgentSendMessageReply)
	err := c.cc.Invoke(ctx, AIAgent_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentClient) GetChatHistory(ctx context.Context, in *AIAgentGetChatHistoryRequest, opts ...grpc.CallOption) (*AIAgentGetChatHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIAgentGetChatHistoryReply)
	err := c.cc.Invoke(ctx, AIAgent_GetChatHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentClient) GetFAQList(ctx context.Context, in *AIAgentGetFAQListRequest, opts ...grpc.CallOption) (*AIAgentGetFAQListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIAgentGetFAQListReply)
	err := c.cc.Invoke(ctx, AIAgent_GetFAQList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentClient) RateService(ctx context.Context, in *AIAgentRateServiceRequest, opts ...grpc.CallOption) (*AIAgentRateServiceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIAgentRateServiceReply)
	err := c.cc.Invoke(ctx, AIAgent_RateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIAgentClient) GetSuggestedQuestions(ctx context.Context, in *AIAgentGetSuggestedQuestionsRequest, opts ...grpc.CallOption) (*AIAgentGetSuggestedQuestionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AIAgentGetSuggestedQuestionsReply)
	err := c.cc.Invoke(ctx, AIAgent_GetSuggestedQuestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIAgentServer is the server API for AIAgent service.
// All implementations must embed UnimplementedAIAgentServer
// for forward compatibility
//
// AI智能体客服服务
type AIAgentServer interface {
	// 发送消息给AI客服
	SendMessage(context.Context, *AIAgentSendMessageRequest) (*AIAgentSendMessageReply, error)
	// 获取聊天历史
	GetChatHistory(context.Context, *AIAgentGetChatHistoryRequest) (*AIAgentGetChatHistoryReply, error)
	// 获取常见问题列表
	GetFAQList(context.Context, *AIAgentGetFAQListRequest) (*AIAgentGetFAQListReply, error)
	// 评价客服服务
	RateService(context.Context, *AIAgentRateServiceRequest) (*AIAgentRateServiceReply, error)
	// 获取智能推荐问题
	GetSuggestedQuestions(context.Context, *AIAgentGetSuggestedQuestionsRequest) (*AIAgentGetSuggestedQuestionsReply, error)
	mustEmbedUnimplementedAIAgentServer()
}

// UnimplementedAIAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAIAgentServer struct {
}

func (UnimplementedAIAgentServer) SendMessage(context.Context, *AIAgentSendMessageRequest) (*AIAgentSendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAIAgentServer) GetChatHistory(context.Context, *AIAgentGetChatHistoryRequest) (*AIAgentGetChatHistoryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChatHistory not implemented")
}
func (UnimplementedAIAgentServer) GetFAQList(context.Context, *AIAgentGetFAQListRequest) (*AIAgentGetFAQListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFAQList not implemented")
}
func (UnimplementedAIAgentServer) RateService(context.Context, *AIAgentRateServiceRequest) (*AIAgentRateServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RateService not implemented")
}
func (UnimplementedAIAgentServer) GetSuggestedQuestions(context.Context, *AIAgentGetSuggestedQuestionsRequest) (*AIAgentGetSuggestedQuestionsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSuggestedQuestions not implemented")
}
func (UnimplementedAIAgentServer) mustEmbedUnimplementedAIAgentServer() {}

// UnsafeAIAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIAgentServer will
// result in compilation errors.
type UnsafeAIAgentServer interface {
	mustEmbedUnimplementedAIAgentServer()
}

func RegisterAIAgentServer(s grpc.ServiceRegistrar, srv AIAgentServer) {
	s.RegisterService(&AIAgent_ServiceDesc, srv)
}

func _AIAgent_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAgentSendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgent_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentServer).SendMessage(ctx, req.(*AIAgentSendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgent_GetChatHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAgentGetChatHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentServer).GetChatHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgent_GetChatHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentServer).GetChatHistory(ctx, req.(*AIAgentGetChatHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgent_GetFAQList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAgentGetFAQListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentServer).GetFAQList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgent_GetFAQList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentServer).GetFAQList(ctx, req.(*AIAgentGetFAQListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgent_RateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAgentRateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentServer).RateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgent_RateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentServer).RateService(ctx, req.(*AIAgentRateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIAgent_GetSuggestedQuestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AIAgentGetSuggestedQuestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIAgentServer).GetSuggestedQuestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIAgent_GetSuggestedQuestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIAgentServer).GetSuggestedQuestions(ctx, req.(*AIAgentGetSuggestedQuestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIAgent_ServiceDesc is the grpc.ServiceDesc for AIAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.AIAgent",
	HandlerType: (*AIAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _AIAgent_SendMessage_Handler,
		},
		{
			MethodName: "GetChatHistory",
			Handler:    _AIAgent_GetChatHistory_Handler,
		},
		{
			MethodName: "GetFAQList",
			Handler:    _AIAgent_GetFAQList_Handler,
		},
		{
			MethodName: "RateService",
			Handler:    _AIAgent_RateService_Handler,
		},
		{
			MethodName: "GetSuggestedQuestions",
			Handler:    _AIAgent_GetSuggestedQuestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/ai_agent.proto",
}
