// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: api/rider/v1/appeal.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationAppealCancelAppeal = "/api.rider.v1.Appeal/CancelAppeal"
const OperationAppealGetAppealDetail = "/api.rider.v1.Appeal/GetAppealDetail"
const OperationAppealGetAppealTypes = "/api.rider.v1.Appeal/GetAppealTypes"
const OperationAppealGetAppeals = "/api.rider.v1.Appeal/GetAppeals"
const OperationAppealGetExceptionOrders = "/api.rider.v1.Appeal/GetExceptionOrders"
const OperationAppealSubmitExceptionReport = "/api.rider.v1.Appeal/SubmitExceptionReport"
const OperationAppealSubmitOrderAppeal = "/api.rider.v1.Appeal/SubmitOrderAppeal"
const OperationAppealSubmitPenaltyAppeal = "/api.rider.v1.Appeal/SubmitPenaltyAppeal"

type AppealHTTPServer interface {
	// CancelAppeal 取消申诉
	CancelAppeal(context.Context, *CancelAppealRequest) (*CancelAppealReply, error)
	// GetAppealDetail 获取申诉详情
	GetAppealDetail(context.Context, *GetAppealDetailRequest) (*GetAppealDetailReply, error)
	// GetAppealTypes 获取申诉类型列表
	GetAppealTypes(context.Context, *GetAppealTypesRequest) (*GetAppealTypesReply, error)
	// GetAppeals 获取申诉列表
	GetAppeals(context.Context, *GetAppealsRequest) (*GetAppealsReply, error)
	// GetExceptionOrders 获取异常订单列表
	GetExceptionOrders(context.Context, *GetExceptionOrdersRequest) (*GetExceptionOrdersReply, error)
	// SubmitExceptionReport 提交异常报备
	SubmitExceptionReport(context.Context, *SubmitExceptionReportRequest) (*SubmitExceptionReportReply, error)
	// SubmitOrderAppeal 提交订单申诉
	SubmitOrderAppeal(context.Context, *SubmitOrderAppealRequest) (*SubmitOrderAppealReply, error)
	// SubmitPenaltyAppeal 提交处罚申诉
	SubmitPenaltyAppeal(context.Context, *SubmitPenaltyAppealRequest) (*SubmitPenaltyAppealReply, error)
}

func RegisterAppealHTTPServer(s *http.Server, srv AppealHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/appeal/order", _Appeal_SubmitOrderAppeal0_HTTP_Handler(srv))
	r.POST("/rider/v1/appeal/penalty", _Appeal_SubmitPenaltyAppeal0_HTTP_Handler(srv))
	r.GET("/rider/v1/appeals", _Appeal_GetAppeals0_HTTP_Handler(srv))
	r.GET("/rider/v1/appeal/{appeal_id}", _Appeal_GetAppealDetail0_HTTP_Handler(srv))
	r.POST("/rider/v1/appeal/{appeal_id}/cancel", _Appeal_CancelAppeal0_HTTP_Handler(srv))
	r.GET("/rider/v1/appeal/types", _Appeal_GetAppealTypes0_HTTP_Handler(srv))
	r.GET("/rider/v1/exception/orders", _Appeal_GetExceptionOrders0_HTTP_Handler(srv))
	r.POST("/rider/v1/exception/report", _Appeal_SubmitExceptionReport0_HTTP_Handler(srv))
}

func _Appeal_SubmitOrderAppeal0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitOrderAppealRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealSubmitOrderAppeal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitOrderAppeal(ctx, req.(*SubmitOrderAppealRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitOrderAppealReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_SubmitPenaltyAppeal0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitPenaltyAppealRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealSubmitPenaltyAppeal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitPenaltyAppeal(ctx, req.(*SubmitPenaltyAppealRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitPenaltyAppealReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_GetAppeals0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppealsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealGetAppeals)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppeals(ctx, req.(*GetAppealsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppealsReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_GetAppealDetail0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppealDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealGetAppealDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppealDetail(ctx, req.(*GetAppealDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppealDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_CancelAppeal0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelAppealRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealCancelAppeal)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelAppeal(ctx, req.(*CancelAppealRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelAppealReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_GetAppealTypes0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAppealTypesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealGetAppealTypes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAppealTypes(ctx, req.(*GetAppealTypesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAppealTypesReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_GetExceptionOrders0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetExceptionOrdersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealGetExceptionOrders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetExceptionOrders(ctx, req.(*GetExceptionOrdersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetExceptionOrdersReply)
		return ctx.Result(200, reply)
	}
}

func _Appeal_SubmitExceptionReport0_HTTP_Handler(srv AppealHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitExceptionReportRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationAppealSubmitExceptionReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitExceptionReport(ctx, req.(*SubmitExceptionReportRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitExceptionReportReply)
		return ctx.Result(200, reply)
	}
}

type AppealHTTPClient interface {
	// CancelAppeal 取消申诉
	CancelAppeal(ctx context.Context, req *CancelAppealRequest, opts ...http.CallOption) (rsp *CancelAppealReply, err error)
	// GetAppealDetail 获取申诉详情
	GetAppealDetail(ctx context.Context, req *GetAppealDetailRequest, opts ...http.CallOption) (rsp *GetAppealDetailReply, err error)
	// GetAppealTypes 获取申诉类型列表
	GetAppealTypes(ctx context.Context, req *GetAppealTypesRequest, opts ...http.CallOption) (rsp *GetAppealTypesReply, err error)
	// GetAppeals 获取申诉列表
	GetAppeals(ctx context.Context, req *GetAppealsRequest, opts ...http.CallOption) (rsp *GetAppealsReply, err error)
	// GetExceptionOrders 获取异常订单列表
	GetExceptionOrders(ctx context.Context, req *GetExceptionOrdersRequest, opts ...http.CallOption) (rsp *GetExceptionOrdersReply, err error)
	// SubmitExceptionReport 提交异常报备
	SubmitExceptionReport(ctx context.Context, req *SubmitExceptionReportRequest, opts ...http.CallOption) (rsp *SubmitExceptionReportReply, err error)
	// SubmitOrderAppeal 提交订单申诉
	SubmitOrderAppeal(ctx context.Context, req *SubmitOrderAppealRequest, opts ...http.CallOption) (rsp *SubmitOrderAppealReply, err error)
	// SubmitPenaltyAppeal 提交处罚申诉
	SubmitPenaltyAppeal(ctx context.Context, req *SubmitPenaltyAppealRequest, opts ...http.CallOption) (rsp *SubmitPenaltyAppealReply, err error)
}

type AppealHTTPClientImpl struct {
	cc *http.Client
}

func NewAppealHTTPClient(client *http.Client) AppealHTTPClient {
	return &AppealHTTPClientImpl{client}
}

// CancelAppeal 取消申诉
func (c *AppealHTTPClientImpl) CancelAppeal(ctx context.Context, in *CancelAppealRequest, opts ...http.CallOption) (*CancelAppealReply, error) {
	var out CancelAppealReply
	pattern := "/rider/v1/appeal/{appeal_id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppealCancelAppeal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAppealDetail 获取申诉详情
func (c *AppealHTTPClientImpl) GetAppealDetail(ctx context.Context, in *GetAppealDetailRequest, opts ...http.CallOption) (*GetAppealDetailReply, error) {
	var out GetAppealDetailReply
	pattern := "/rider/v1/appeal/{appeal_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAppealGetAppealDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAppealTypes 获取申诉类型列表
func (c *AppealHTTPClientImpl) GetAppealTypes(ctx context.Context, in *GetAppealTypesRequest, opts ...http.CallOption) (*GetAppealTypesReply, error) {
	var out GetAppealTypesReply
	pattern := "/rider/v1/appeal/types"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAppealGetAppealTypes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAppeals 获取申诉列表
func (c *AppealHTTPClientImpl) GetAppeals(ctx context.Context, in *GetAppealsRequest, opts ...http.CallOption) (*GetAppealsReply, error) {
	var out GetAppealsReply
	pattern := "/rider/v1/appeals"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAppealGetAppeals))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetExceptionOrders 获取异常订单列表
func (c *AppealHTTPClientImpl) GetExceptionOrders(ctx context.Context, in *GetExceptionOrdersRequest, opts ...http.CallOption) (*GetExceptionOrdersReply, error) {
	var out GetExceptionOrdersReply
	pattern := "/rider/v1/exception/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationAppealGetExceptionOrders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitExceptionReport 提交异常报备
func (c *AppealHTTPClientImpl) SubmitExceptionReport(ctx context.Context, in *SubmitExceptionReportRequest, opts ...http.CallOption) (*SubmitExceptionReportReply, error) {
	var out SubmitExceptionReportReply
	pattern := "/rider/v1/exception/report"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppealSubmitExceptionReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitOrderAppeal 提交订单申诉
func (c *AppealHTTPClientImpl) SubmitOrderAppeal(ctx context.Context, in *SubmitOrderAppealRequest, opts ...http.CallOption) (*SubmitOrderAppealReply, error) {
	var out SubmitOrderAppealReply
	pattern := "/rider/v1/appeal/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppealSubmitOrderAppeal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitPenaltyAppeal 提交处罚申诉
func (c *AppealHTTPClientImpl) SubmitPenaltyAppeal(ctx context.Context, in *SubmitPenaltyAppealRequest, opts ...http.CallOption) (*SubmitPenaltyAppealReply, error) {
	var out SubmitPenaltyAppealReply
	pattern := "/rider/v1/appeal/penalty"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationAppealSubmitPenaltyAppeal))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
