// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: api/rider/v1/appeal.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Appeal_SubmitOrderAppeal_FullMethodName     = "/api.rider.v1.Appeal/SubmitOrderAppeal"
	Appeal_SubmitPenaltyAppeal_FullMethodName   = "/api.rider.v1.Appeal/SubmitPenaltyAppeal"
	Appeal_GetAppeals_FullMethodName            = "/api.rider.v1.Appeal/GetAppeals"
	Appeal_GetAppealDetail_FullMethodName       = "/api.rider.v1.Appeal/GetAppealDetail"
	Appeal_CancelAppeal_FullMethodName          = "/api.rider.v1.Appeal/CancelAppeal"
	Appeal_GetAppealTypes_FullMethodName        = "/api.rider.v1.Appeal/GetAppealTypes"
	Appeal_GetExceptionOrders_FullMethodName    = "/api.rider.v1.Appeal/GetExceptionOrders"
	Appeal_SubmitExceptionReport_FullMethodName = "/api.rider.v1.Appeal/SubmitExceptionReport"
)

// AppealClient is the client API for Appeal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 申诉服务
type AppealClient interface {
	// 提交订单申诉
	SubmitOrderAppeal(ctx context.Context, in *SubmitOrderAppealRequest, opts ...grpc.CallOption) (*SubmitOrderAppealReply, error)
	// 提交处罚申诉
	SubmitPenaltyAppeal(ctx context.Context, in *SubmitPenaltyAppealRequest, opts ...grpc.CallOption) (*SubmitPenaltyAppealReply, error)
	// 获取申诉列表
	GetAppeals(ctx context.Context, in *GetAppealsRequest, opts ...grpc.CallOption) (*GetAppealsReply, error)
	// 获取申诉详情
	GetAppealDetail(ctx context.Context, in *GetAppealDetailRequest, opts ...grpc.CallOption) (*GetAppealDetailReply, error)
	// 取消申诉
	CancelAppeal(ctx context.Context, in *CancelAppealRequest, opts ...grpc.CallOption) (*CancelAppealReply, error)
	// 获取申诉类型列表
	GetAppealTypes(ctx context.Context, in *GetAppealTypesRequest, opts ...grpc.CallOption) (*GetAppealTypesReply, error)
	// 获取异常订单列表
	GetExceptionOrders(ctx context.Context, in *GetExceptionOrdersRequest, opts ...grpc.CallOption) (*GetExceptionOrdersReply, error)
	// 提交异常报备
	SubmitExceptionReport(ctx context.Context, in *SubmitExceptionReportRequest, opts ...grpc.CallOption) (*SubmitExceptionReportReply, error)
}

type appealClient struct {
	cc grpc.ClientConnInterface
}

func NewAppealClient(cc grpc.ClientConnInterface) AppealClient {
	return &appealClient{cc}
}

func (c *appealClient) SubmitOrderAppeal(ctx context.Context, in *SubmitOrderAppealRequest, opts ...grpc.CallOption) (*SubmitOrderAppealReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitOrderAppealReply)
	err := c.cc.Invoke(ctx, Appeal_SubmitOrderAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) SubmitPenaltyAppeal(ctx context.Context, in *SubmitPenaltyAppealRequest, opts ...grpc.CallOption) (*SubmitPenaltyAppealReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPenaltyAppealReply)
	err := c.cc.Invoke(ctx, Appeal_SubmitPenaltyAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) GetAppeals(ctx context.Context, in *GetAppealsRequest, opts ...grpc.CallOption) (*GetAppealsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppealsReply)
	err := c.cc.Invoke(ctx, Appeal_GetAppeals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) GetAppealDetail(ctx context.Context, in *GetAppealDetailRequest, opts ...grpc.CallOption) (*GetAppealDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppealDetailReply)
	err := c.cc.Invoke(ctx, Appeal_GetAppealDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) CancelAppeal(ctx context.Context, in *CancelAppealRequest, opts ...grpc.CallOption) (*CancelAppealReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelAppealReply)
	err := c.cc.Invoke(ctx, Appeal_CancelAppeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) GetAppealTypes(ctx context.Context, in *GetAppealTypesRequest, opts ...grpc.CallOption) (*GetAppealTypesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppealTypesReply)
	err := c.cc.Invoke(ctx, Appeal_GetAppealTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) GetExceptionOrders(ctx context.Context, in *GetExceptionOrdersRequest, opts ...grpc.CallOption) (*GetExceptionOrdersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetExceptionOrdersReply)
	err := c.cc.Invoke(ctx, Appeal_GetExceptionOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *appealClient) SubmitExceptionReport(ctx context.Context, in *SubmitExceptionReportRequest, opts ...grpc.CallOption) (*SubmitExceptionReportReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitExceptionReportReply)
	err := c.cc.Invoke(ctx, Appeal_SubmitExceptionReport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppealServer is the server API for Appeal service.
// All implementations must embed UnimplementedAppealServer
// for forward compatibility
//
// 申诉服务
type AppealServer interface {
	// 提交订单申诉
	SubmitOrderAppeal(context.Context, *SubmitOrderAppealRequest) (*SubmitOrderAppealReply, error)
	// 提交处罚申诉
	SubmitPenaltyAppeal(context.Context, *SubmitPenaltyAppealRequest) (*SubmitPenaltyAppealReply, error)
	// 获取申诉列表
	GetAppeals(context.Context, *GetAppealsRequest) (*GetAppealsReply, error)
	// 获取申诉详情
	GetAppealDetail(context.Context, *GetAppealDetailRequest) (*GetAppealDetailReply, error)
	// 取消申诉
	CancelAppeal(context.Context, *CancelAppealRequest) (*CancelAppealReply, error)
	// 获取申诉类型列表
	GetAppealTypes(context.Context, *GetAppealTypesRequest) (*GetAppealTypesReply, error)
	// 获取异常订单列表
	GetExceptionOrders(context.Context, *GetExceptionOrdersRequest) (*GetExceptionOrdersReply, error)
	// 提交异常报备
	SubmitExceptionReport(context.Context, *SubmitExceptionReportRequest) (*SubmitExceptionReportReply, error)
	mustEmbedUnimplementedAppealServer()
}

// UnimplementedAppealServer must be embedded to have forward compatible implementations.
type UnimplementedAppealServer struct {
}

func (UnimplementedAppealServer) SubmitOrderAppeal(context.Context, *SubmitOrderAppealRequest) (*SubmitOrderAppealReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrderAppeal not implemented")
}
func (UnimplementedAppealServer) SubmitPenaltyAppeal(context.Context, *SubmitPenaltyAppealRequest) (*SubmitPenaltyAppealReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPenaltyAppeal not implemented")
}
func (UnimplementedAppealServer) GetAppeals(context.Context, *GetAppealsRequest) (*GetAppealsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppeals not implemented")
}
func (UnimplementedAppealServer) GetAppealDetail(context.Context, *GetAppealDetailRequest) (*GetAppealDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppealDetail not implemented")
}
func (UnimplementedAppealServer) CancelAppeal(context.Context, *CancelAppealRequest) (*CancelAppealReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAppeal not implemented")
}
func (UnimplementedAppealServer) GetAppealTypes(context.Context, *GetAppealTypesRequest) (*GetAppealTypesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppealTypes not implemented")
}
func (UnimplementedAppealServer) GetExceptionOrders(context.Context, *GetExceptionOrdersRequest) (*GetExceptionOrdersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExceptionOrders not implemented")
}
func (UnimplementedAppealServer) SubmitExceptionReport(context.Context, *SubmitExceptionReportRequest) (*SubmitExceptionReportReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitExceptionReport not implemented")
}
func (UnimplementedAppealServer) mustEmbedUnimplementedAppealServer() {}

// UnsafeAppealServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppealServer will
// result in compilation errors.
type UnsafeAppealServer interface {
	mustEmbedUnimplementedAppealServer()
}

func RegisterAppealServer(s grpc.ServiceRegistrar, srv AppealServer) {
	s.RegisterService(&Appeal_ServiceDesc, srv)
}

func _Appeal_SubmitOrderAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).SubmitOrderAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_SubmitOrderAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).SubmitOrderAppeal(ctx, req.(*SubmitOrderAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_SubmitPenaltyAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPenaltyAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).SubmitPenaltyAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_SubmitPenaltyAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).SubmitPenaltyAppeal(ctx, req.(*SubmitPenaltyAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_GetAppeals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppealsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).GetAppeals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_GetAppeals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).GetAppeals(ctx, req.(*GetAppealsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_GetAppealDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppealDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).GetAppealDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_GetAppealDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).GetAppealDetail(ctx, req.(*GetAppealDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_CancelAppeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelAppealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).CancelAppeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_CancelAppeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).CancelAppeal(ctx, req.(*CancelAppealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_GetAppealTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppealTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).GetAppealTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_GetAppealTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).GetAppealTypes(ctx, req.(*GetAppealTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_GetExceptionOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExceptionOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).GetExceptionOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_GetExceptionOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).GetExceptionOrders(ctx, req.(*GetExceptionOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Appeal_SubmitExceptionReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitExceptionReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppealServer).SubmitExceptionReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Appeal_SubmitExceptionReport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppealServer).SubmitExceptionReport(ctx, req.(*SubmitExceptionReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Appeal_ServiceDesc is the grpc.ServiceDesc for Appeal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Appeal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Appeal",
	HandlerType: (*AppealServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrderAppeal",
			Handler:    _Appeal_SubmitOrderAppeal_Handler,
		},
		{
			MethodName: "SubmitPenaltyAppeal",
			Handler:    _Appeal_SubmitPenaltyAppeal_Handler,
		},
		{
			MethodName: "GetAppeals",
			Handler:    _Appeal_GetAppeals_Handler,
		},
		{
			MethodName: "GetAppealDetail",
			Handler:    _Appeal_GetAppealDetail_Handler,
		},
		{
			MethodName: "CancelAppeal",
			Handler:    _Appeal_CancelAppeal_Handler,
		},
		{
			MethodName: "GetAppealTypes",
			Handler:    _Appeal_GetAppealTypes_Handler,
		},
		{
			MethodName: "GetExceptionOrders",
			Handler:    _Appeal_GetExceptionOrders_Handler,
		},
		{
			MethodName: "SubmitExceptionReport",
			Handler:    _Appeal_SubmitExceptionReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rider/v1/appeal.proto",
}
