// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/deactivation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationDeactivationServiceApplyDeactivation = "/api.rider.v1.DeactivationService/ApplyDeactivation"
const OperationDeactivationServiceCancelDeactivation = "/api.rider.v1.DeactivationService/CancelDeactivation"
const OperationDeactivationServiceGetDeactivationDetail = "/api.rider.v1.DeactivationService/GetDeactivationDetail"
const OperationDeactivationServiceGetDeactivationList = "/api.rider.v1.DeactivationService/GetDeactivationList"
const OperationDeactivationServiceGetDeactivationReasons = "/api.rider.v1.DeactivationService/GetDeactivationReasons"
const OperationDeactivationServiceGetDeactivationStatistics = "/api.rider.v1.DeactivationService/GetDeactivationStatistics"
const OperationDeactivationServiceGetDeactivationStatus = "/api.rider.v1.DeactivationService/GetDeactivationStatus"
const OperationDeactivationServiceReviewDeactivation = "/api.rider.v1.DeactivationService/ReviewDeactivation"

type DeactivationServiceHTTPServer interface {
	// ApplyDeactivation 申请注销
	ApplyDeactivation(context.Context, *ApplyDeactivationRequest) (*ApplyDeactivationReply, error)
	// CancelDeactivation 取消注销申请
	CancelDeactivation(context.Context, *CancelDeactivationRequest) (*CancelDeactivationReply, error)
	// GetDeactivationDetail 获取注销详情
	GetDeactivationDetail(context.Context, *GetDeactivationDetailRequest) (*GetDeactivationDetailReply, error)
	// GetDeactivationList 获取注销申请列表
	GetDeactivationList(context.Context, *GetDeactivationListRequest) (*GetDeactivationListReply, error)
	// GetDeactivationReasons 获取注销原因列表
	GetDeactivationReasons(context.Context, *GetDeactivationReasonsRequest) (*GetDeactivationReasonsReply, error)
	// GetDeactivationStatistics 获取注销统计
	GetDeactivationStatistics(context.Context, *GetDeactivationStatisticsRequest) (*GetDeactivationStatisticsReply, error)
	// GetDeactivationStatus 获取注销状态
	GetDeactivationStatus(context.Context, *GetDeactivationStatusRequest) (*GetDeactivationStatusReply, error)
	// ReviewDeactivation 审核注销申请
	ReviewDeactivation(context.Context, *ReviewDeactivationRequest) (*ReviewDeactivationReply, error)
}

func RegisterDeactivationServiceHTTPServer(s *http.Server, srv DeactivationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/deactivation/apply", _DeactivationService_ApplyDeactivation0_HTTP_Handler(srv))
	r.GET("/rider/v1/deactivation/status", _DeactivationService_GetDeactivationStatus0_HTTP_Handler(srv))
	r.POST("/rider/v1/deactivation/cancel", _DeactivationService_CancelDeactivation0_HTTP_Handler(srv))
	r.GET("/rider/v1/deactivation/reasons", _DeactivationService_GetDeactivationReasons0_HTTP_Handler(srv))
	r.GET("/rider/v1/admin/deactivation/list", _DeactivationService_GetDeactivationList0_HTTP_Handler(srv))
	r.POST("/rider/v1/admin/deactivation/review", _DeactivationService_ReviewDeactivation0_HTTP_Handler(srv))
	r.GET("/rider/v1/admin/deactivation/detail/{deactivation_id}", _DeactivationService_GetDeactivationDetail0_HTTP_Handler(srv))
	r.GET("/rider/v1/admin/deactivation/statistics", _DeactivationService_GetDeactivationStatistics0_HTTP_Handler(srv))
}

func _DeactivationService_ApplyDeactivation0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ApplyDeactivationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceApplyDeactivation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ApplyDeactivation(ctx, req.(*ApplyDeactivationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ApplyDeactivationReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_GetDeactivationStatus0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeactivationStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceGetDeactivationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeactivationStatus(ctx, req.(*GetDeactivationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeactivationStatusReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_CancelDeactivation0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelDeactivationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceCancelDeactivation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelDeactivation(ctx, req.(*CancelDeactivationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelDeactivationReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_GetDeactivationReasons0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeactivationReasonsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceGetDeactivationReasons)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeactivationReasons(ctx, req.(*GetDeactivationReasonsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeactivationReasonsReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_GetDeactivationList0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeactivationListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceGetDeactivationList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeactivationList(ctx, req.(*GetDeactivationListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeactivationListReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_ReviewDeactivation0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReviewDeactivationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceReviewDeactivation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReviewDeactivation(ctx, req.(*ReviewDeactivationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReviewDeactivationReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_GetDeactivationDetail0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeactivationDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceGetDeactivationDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeactivationDetail(ctx, req.(*GetDeactivationDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeactivationDetailReply)
		return ctx.Result(200, reply)
	}
}

func _DeactivationService_GetDeactivationStatistics0_HTTP_Handler(srv DeactivationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetDeactivationStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationDeactivationServiceGetDeactivationStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetDeactivationStatistics(ctx, req.(*GetDeactivationStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetDeactivationStatisticsReply)
		return ctx.Result(200, reply)
	}
}

type DeactivationServiceHTTPClient interface {
	// ApplyDeactivation 申请注销
	ApplyDeactivation(ctx context.Context, req *ApplyDeactivationRequest, opts ...http.CallOption) (rsp *ApplyDeactivationReply, err error)
	// CancelDeactivation 取消注销申请
	CancelDeactivation(ctx context.Context, req *CancelDeactivationRequest, opts ...http.CallOption) (rsp *CancelDeactivationReply, err error)
	// GetDeactivationDetail 获取注销详情
	GetDeactivationDetail(ctx context.Context, req *GetDeactivationDetailRequest, opts ...http.CallOption) (rsp *GetDeactivationDetailReply, err error)
	// GetDeactivationList 获取注销申请列表
	GetDeactivationList(ctx context.Context, req *GetDeactivationListRequest, opts ...http.CallOption) (rsp *GetDeactivationListReply, err error)
	// GetDeactivationReasons 获取注销原因列表
	GetDeactivationReasons(ctx context.Context, req *GetDeactivationReasonsRequest, opts ...http.CallOption) (rsp *GetDeactivationReasonsReply, err error)
	// GetDeactivationStatistics 获取注销统计
	GetDeactivationStatistics(ctx context.Context, req *GetDeactivationStatisticsRequest, opts ...http.CallOption) (rsp *GetDeactivationStatisticsReply, err error)
	// GetDeactivationStatus 获取注销状态
	GetDeactivationStatus(ctx context.Context, req *GetDeactivationStatusRequest, opts ...http.CallOption) (rsp *GetDeactivationStatusReply, err error)
	// ReviewDeactivation 审核注销申请
	ReviewDeactivation(ctx context.Context, req *ReviewDeactivationRequest, opts ...http.CallOption) (rsp *ReviewDeactivationReply, err error)
}

type DeactivationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewDeactivationServiceHTTPClient(client *http.Client) DeactivationServiceHTTPClient {
	return &DeactivationServiceHTTPClientImpl{client}
}

// ApplyDeactivation 申请注销
func (c *DeactivationServiceHTTPClientImpl) ApplyDeactivation(ctx context.Context, in *ApplyDeactivationRequest, opts ...http.CallOption) (*ApplyDeactivationReply, error) {
	var out ApplyDeactivationReply
	pattern := "/rider/v1/deactivation/apply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeactivationServiceApplyDeactivation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelDeactivation 取消注销申请
func (c *DeactivationServiceHTTPClientImpl) CancelDeactivation(ctx context.Context, in *CancelDeactivationRequest, opts ...http.CallOption) (*CancelDeactivationReply, error) {
	var out CancelDeactivationReply
	pattern := "/rider/v1/deactivation/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeactivationServiceCancelDeactivation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeactivationDetail 获取注销详情
func (c *DeactivationServiceHTTPClientImpl) GetDeactivationDetail(ctx context.Context, in *GetDeactivationDetailRequest, opts ...http.CallOption) (*GetDeactivationDetailReply, error) {
	var out GetDeactivationDetailReply
	pattern := "/rider/v1/admin/deactivation/detail/{deactivation_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeactivationServiceGetDeactivationDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeactivationList 获取注销申请列表
func (c *DeactivationServiceHTTPClientImpl) GetDeactivationList(ctx context.Context, in *GetDeactivationListRequest, opts ...http.CallOption) (*GetDeactivationListReply, error) {
	var out GetDeactivationListReply
	pattern := "/rider/v1/admin/deactivation/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeactivationServiceGetDeactivationList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeactivationReasons 获取注销原因列表
func (c *DeactivationServiceHTTPClientImpl) GetDeactivationReasons(ctx context.Context, in *GetDeactivationReasonsRequest, opts ...http.CallOption) (*GetDeactivationReasonsReply, error) {
	var out GetDeactivationReasonsReply
	pattern := "/rider/v1/deactivation/reasons"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeactivationServiceGetDeactivationReasons))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeactivationStatistics 获取注销统计
func (c *DeactivationServiceHTTPClientImpl) GetDeactivationStatistics(ctx context.Context, in *GetDeactivationStatisticsRequest, opts ...http.CallOption) (*GetDeactivationStatisticsReply, error) {
	var out GetDeactivationStatisticsReply
	pattern := "/rider/v1/admin/deactivation/statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeactivationServiceGetDeactivationStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetDeactivationStatus 获取注销状态
func (c *DeactivationServiceHTTPClientImpl) GetDeactivationStatus(ctx context.Context, in *GetDeactivationStatusRequest, opts ...http.CallOption) (*GetDeactivationStatusReply, error) {
	var out GetDeactivationStatusReply
	pattern := "/rider/v1/deactivation/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationDeactivationServiceGetDeactivationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReviewDeactivation 审核注销申请
func (c *DeactivationServiceHTTPClientImpl) ReviewDeactivation(ctx context.Context, in *ReviewDeactivationRequest, opts ...http.CallOption) (*ReviewDeactivationReply, error) {
	var out ReviewDeactivationReply
	pattern := "/rider/v1/admin/deactivation/review"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationDeactivationServiceReviewDeactivation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
