// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/deactivation.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	DeactivationService_ApplyDeactivation_FullMethodName         = "/api.rider.v1.DeactivationService/ApplyDeactivation"
	DeactivationService_GetDeactivationStatus_FullMethodName     = "/api.rider.v1.DeactivationService/GetDeactivationStatus"
	DeactivationService_CancelDeactivation_FullMethodName        = "/api.rider.v1.DeactivationService/CancelDeactivation"
	DeactivationService_GetDeactivationReasons_FullMethodName    = "/api.rider.v1.DeactivationService/GetDeactivationReasons"
	DeactivationService_GetDeactivationList_FullMethodName       = "/api.rider.v1.DeactivationService/GetDeactivationList"
	DeactivationService_ReviewDeactivation_FullMethodName        = "/api.rider.v1.DeactivationService/ReviewDeactivation"
	DeactivationService_GetDeactivationDetail_FullMethodName     = "/api.rider.v1.DeactivationService/GetDeactivationDetail"
	DeactivationService_GetDeactivationStatistics_FullMethodName = "/api.rider.v1.DeactivationService/GetDeactivationStatistics"
)

// DeactivationServiceClient is the client API for DeactivationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 骑手注销服务
type DeactivationServiceClient interface {
	// 申请注销
	ApplyDeactivation(ctx context.Context, in *ApplyDeactivationRequest, opts ...grpc.CallOption) (*ApplyDeactivationReply, error)
	// 获取注销状态
	GetDeactivationStatus(ctx context.Context, in *GetDeactivationStatusRequest, opts ...grpc.CallOption) (*GetDeactivationStatusReply, error)
	// 取消注销申请
	CancelDeactivation(ctx context.Context, in *CancelDeactivationRequest, opts ...grpc.CallOption) (*CancelDeactivationReply, error)
	// 获取注销原因列表
	GetDeactivationReasons(ctx context.Context, in *GetDeactivationReasonsRequest, opts ...grpc.CallOption) (*GetDeactivationReasonsReply, error)
	// 获取注销申请列表
	GetDeactivationList(ctx context.Context, in *GetDeactivationListRequest, opts ...grpc.CallOption) (*GetDeactivationListReply, error)
	// 审核注销申请
	ReviewDeactivation(ctx context.Context, in *ReviewDeactivationRequest, opts ...grpc.CallOption) (*ReviewDeactivationReply, error)
	// 获取注销详情
	GetDeactivationDetail(ctx context.Context, in *GetDeactivationDetailRequest, opts ...grpc.CallOption) (*GetDeactivationDetailReply, error)
	// 获取注销统计
	GetDeactivationStatistics(ctx context.Context, in *GetDeactivationStatisticsRequest, opts ...grpc.CallOption) (*GetDeactivationStatisticsReply, error)
}

type deactivationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeactivationServiceClient(cc grpc.ClientConnInterface) DeactivationServiceClient {
	return &deactivationServiceClient{cc}
}

func (c *deactivationServiceClient) ApplyDeactivation(ctx context.Context, in *ApplyDeactivationRequest, opts ...grpc.CallOption) (*ApplyDeactivationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyDeactivationReply)
	err := c.cc.Invoke(ctx, DeactivationService_ApplyDeactivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) GetDeactivationStatus(ctx context.Context, in *GetDeactivationStatusRequest, opts ...grpc.CallOption) (*GetDeactivationStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeactivationStatusReply)
	err := c.cc.Invoke(ctx, DeactivationService_GetDeactivationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) CancelDeactivation(ctx context.Context, in *CancelDeactivationRequest, opts ...grpc.CallOption) (*CancelDeactivationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelDeactivationReply)
	err := c.cc.Invoke(ctx, DeactivationService_CancelDeactivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) GetDeactivationReasons(ctx context.Context, in *GetDeactivationReasonsRequest, opts ...grpc.CallOption) (*GetDeactivationReasonsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeactivationReasonsReply)
	err := c.cc.Invoke(ctx, DeactivationService_GetDeactivationReasons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) GetDeactivationList(ctx context.Context, in *GetDeactivationListRequest, opts ...grpc.CallOption) (*GetDeactivationListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeactivationListReply)
	err := c.cc.Invoke(ctx, DeactivationService_GetDeactivationList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) ReviewDeactivation(ctx context.Context, in *ReviewDeactivationRequest, opts ...grpc.CallOption) (*ReviewDeactivationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewDeactivationReply)
	err := c.cc.Invoke(ctx, DeactivationService_ReviewDeactivation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) GetDeactivationDetail(ctx context.Context, in *GetDeactivationDetailRequest, opts ...grpc.CallOption) (*GetDeactivationDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeactivationDetailReply)
	err := c.cc.Invoke(ctx, DeactivationService_GetDeactivationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deactivationServiceClient) GetDeactivationStatistics(ctx context.Context, in *GetDeactivationStatisticsRequest, opts ...grpc.CallOption) (*GetDeactivationStatisticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDeactivationStatisticsReply)
	err := c.cc.Invoke(ctx, DeactivationService_GetDeactivationStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeactivationServiceServer is the server API for DeactivationService service.
// All implementations must embed UnimplementedDeactivationServiceServer
// for forward compatibility
//
// 骑手注销服务
type DeactivationServiceServer interface {
	// 申请注销
	ApplyDeactivation(context.Context, *ApplyDeactivationRequest) (*ApplyDeactivationReply, error)
	// 获取注销状态
	GetDeactivationStatus(context.Context, *GetDeactivationStatusRequest) (*GetDeactivationStatusReply, error)
	// 取消注销申请
	CancelDeactivation(context.Context, *CancelDeactivationRequest) (*CancelDeactivationReply, error)
	// 获取注销原因列表
	GetDeactivationReasons(context.Context, *GetDeactivationReasonsRequest) (*GetDeactivationReasonsReply, error)
	// 获取注销申请列表
	GetDeactivationList(context.Context, *GetDeactivationListRequest) (*GetDeactivationListReply, error)
	// 审核注销申请
	ReviewDeactivation(context.Context, *ReviewDeactivationRequest) (*ReviewDeactivationReply, error)
	// 获取注销详情
	GetDeactivationDetail(context.Context, *GetDeactivationDetailRequest) (*GetDeactivationDetailReply, error)
	// 获取注销统计
	GetDeactivationStatistics(context.Context, *GetDeactivationStatisticsRequest) (*GetDeactivationStatisticsReply, error)
	mustEmbedUnimplementedDeactivationServiceServer()
}

// UnimplementedDeactivationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDeactivationServiceServer struct {
}

func (UnimplementedDeactivationServiceServer) ApplyDeactivation(context.Context, *ApplyDeactivationRequest) (*ApplyDeactivationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyDeactivation not implemented")
}
func (UnimplementedDeactivationServiceServer) GetDeactivationStatus(context.Context, *GetDeactivationStatusRequest) (*GetDeactivationStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeactivationStatus not implemented")
}
func (UnimplementedDeactivationServiceServer) CancelDeactivation(context.Context, *CancelDeactivationRequest) (*CancelDeactivationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelDeactivation not implemented")
}
func (UnimplementedDeactivationServiceServer) GetDeactivationReasons(context.Context, *GetDeactivationReasonsRequest) (*GetDeactivationReasonsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeactivationReasons not implemented")
}
func (UnimplementedDeactivationServiceServer) GetDeactivationList(context.Context, *GetDeactivationListRequest) (*GetDeactivationListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeactivationList not implemented")
}
func (UnimplementedDeactivationServiceServer) ReviewDeactivation(context.Context, *ReviewDeactivationRequest) (*ReviewDeactivationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReviewDeactivation not implemented")
}
func (UnimplementedDeactivationServiceServer) GetDeactivationDetail(context.Context, *GetDeactivationDetailRequest) (*GetDeactivationDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeactivationDetail not implemented")
}
func (UnimplementedDeactivationServiceServer) GetDeactivationStatistics(context.Context, *GetDeactivationStatisticsRequest) (*GetDeactivationStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeactivationStatistics not implemented")
}
func (UnimplementedDeactivationServiceServer) mustEmbedUnimplementedDeactivationServiceServer() {}

// UnsafeDeactivationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeactivationServiceServer will
// result in compilation errors.
type UnsafeDeactivationServiceServer interface {
	mustEmbedUnimplementedDeactivationServiceServer()
}

func RegisterDeactivationServiceServer(s grpc.ServiceRegistrar, srv DeactivationServiceServer) {
	s.RegisterService(&DeactivationService_ServiceDesc, srv)
}

func _DeactivationService_ApplyDeactivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyDeactivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).ApplyDeactivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_ApplyDeactivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).ApplyDeactivation(ctx, req.(*ApplyDeactivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_GetDeactivationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeactivationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).GetDeactivationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_GetDeactivationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).GetDeactivationStatus(ctx, req.(*GetDeactivationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_CancelDeactivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelDeactivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).CancelDeactivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_CancelDeactivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).CancelDeactivation(ctx, req.(*CancelDeactivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_GetDeactivationReasons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeactivationReasonsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).GetDeactivationReasons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_GetDeactivationReasons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).GetDeactivationReasons(ctx, req.(*GetDeactivationReasonsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_GetDeactivationList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeactivationListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).GetDeactivationList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_GetDeactivationList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).GetDeactivationList(ctx, req.(*GetDeactivationListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_ReviewDeactivation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewDeactivationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).ReviewDeactivation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_ReviewDeactivation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).ReviewDeactivation(ctx, req.(*ReviewDeactivationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_GetDeactivationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeactivationDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).GetDeactivationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_GetDeactivationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).GetDeactivationDetail(ctx, req.(*GetDeactivationDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeactivationService_GetDeactivationStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeactivationStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeactivationServiceServer).GetDeactivationStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeactivationService_GetDeactivationStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeactivationServiceServer).GetDeactivationStatistics(ctx, req.(*GetDeactivationStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeactivationService_ServiceDesc is the grpc.ServiceDesc for DeactivationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeactivationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.DeactivationService",
	HandlerType: (*DeactivationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ApplyDeactivation",
			Handler:    _DeactivationService_ApplyDeactivation_Handler,
		},
		{
			MethodName: "GetDeactivationStatus",
			Handler:    _DeactivationService_GetDeactivationStatus_Handler,
		},
		{
			MethodName: "CancelDeactivation",
			Handler:    _DeactivationService_CancelDeactivation_Handler,
		},
		{
			MethodName: "GetDeactivationReasons",
			Handler:    _DeactivationService_GetDeactivationReasons_Handler,
		},
		{
			MethodName: "GetDeactivationList",
			Handler:    _DeactivationService_GetDeactivationList_Handler,
		},
		{
			MethodName: "ReviewDeactivation",
			Handler:    _DeactivationService_ReviewDeactivation_Handler,
		},
		{
			MethodName: "GetDeactivationDetail",
			Handler:    _DeactivationService_GetDeactivationDetail_Handler,
		},
		{
			MethodName: "GetDeactivationStatistics",
			Handler:    _DeactivationService_GetDeactivationStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/deactivation.proto",
}
