// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/income.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Income_CreateIncome_FullMethodName           = "/api.rider.v1.Income/CreateIncome"
	Income_GetIncomeList_FullMethodName          = "/api.rider.v1.Income/GetIncomeList"
	Income_GetTotalIncome_FullMethodName         = "/api.rider.v1.Income/GetTotalIncome"
	Income_ApplyWithdrawal_FullMethodName        = "/api.rider.v1.Income/ApplyWithdrawal"
	Income_GetWithdrawalList_FullMethodName      = "/api.rider.v1.Income/GetWithdrawalList"
	Income_UpdateWithdrawalStatus_FullMethodName = "/api.rider.v1.Income/UpdateWithdrawalStatus"
)

// IncomeClient is the client API for Income service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 收入服务
type IncomeClient interface {
	// 创建收入记录
	CreateIncome(ctx context.Context, in *CreateIncomeRequest, opts ...grpc.CallOption) (*CreateIncomeReply, error)
	// 获取收入列表
	GetIncomeList(ctx context.Context, in *GetIncomeListRequest, opts ...grpc.CallOption) (*GetIncomeListReply, error)
	// 获取总收入
	GetTotalIncome(ctx context.Context, in *GetTotalIncomeRequest, opts ...grpc.CallOption) (*GetTotalIncomeReply, error)
	// 申请提现
	ApplyWithdrawal(ctx context.Context, in *ApplyWithdrawalRequest, opts ...grpc.CallOption) (*ApplyWithdrawalReply, error)
	// 获取提现列表
	GetWithdrawalList(ctx context.Context, in *GetWithdrawalListRequest, opts ...grpc.CallOption) (*GetWithdrawalListReply, error)
	// 更新提现状态
	UpdateWithdrawalStatus(ctx context.Context, in *UpdateWithdrawalStatusRequest, opts ...grpc.CallOption) (*UpdateWithdrawalStatusReply, error)
}

type incomeClient struct {
	cc grpc.ClientConnInterface
}

func NewIncomeClient(cc grpc.ClientConnInterface) IncomeClient {
	return &incomeClient{cc}
}

func (c *incomeClient) CreateIncome(ctx context.Context, in *CreateIncomeRequest, opts ...grpc.CallOption) (*CreateIncomeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIncomeReply)
	err := c.cc.Invoke(ctx, Income_CreateIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incomeClient) GetIncomeList(ctx context.Context, in *GetIncomeListRequest, opts ...grpc.CallOption) (*GetIncomeListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncomeListReply)
	err := c.cc.Invoke(ctx, Income_GetIncomeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incomeClient) GetTotalIncome(ctx context.Context, in *GetTotalIncomeRequest, opts ...grpc.CallOption) (*GetTotalIncomeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTotalIncomeReply)
	err := c.cc.Invoke(ctx, Income_GetTotalIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incomeClient) ApplyWithdrawal(ctx context.Context, in *ApplyWithdrawalRequest, opts ...grpc.CallOption) (*ApplyWithdrawalReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWithdrawalReply)
	err := c.cc.Invoke(ctx, Income_ApplyWithdrawal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incomeClient) GetWithdrawalList(ctx context.Context, in *GetWithdrawalListRequest, opts ...grpc.CallOption) (*GetWithdrawalListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawalListReply)
	err := c.cc.Invoke(ctx, Income_GetWithdrawalList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *incomeClient) UpdateWithdrawalStatus(ctx context.Context, in *UpdateWithdrawalStatusRequest, opts ...grpc.CallOption) (*UpdateWithdrawalStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWithdrawalStatusReply)
	err := c.cc.Invoke(ctx, Income_UpdateWithdrawalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncomeServer is the server API for Income service.
// All implementations must embed UnimplementedIncomeServer
// for forward compatibility
//
// 收入服务
type IncomeServer interface {
	// 创建收入记录
	CreateIncome(context.Context, *CreateIncomeRequest) (*CreateIncomeReply, error)
	// 获取收入列表
	GetIncomeList(context.Context, *GetIncomeListRequest) (*GetIncomeListReply, error)
	// 获取总收入
	GetTotalIncome(context.Context, *GetTotalIncomeRequest) (*GetTotalIncomeReply, error)
	// 申请提现
	ApplyWithdrawal(context.Context, *ApplyWithdrawalRequest) (*ApplyWithdrawalReply, error)
	// 获取提现列表
	GetWithdrawalList(context.Context, *GetWithdrawalListRequest) (*GetWithdrawalListReply, error)
	// 更新提现状态
	UpdateWithdrawalStatus(context.Context, *UpdateWithdrawalStatusRequest) (*UpdateWithdrawalStatusReply, error)
	mustEmbedUnimplementedIncomeServer()
}

// UnimplementedIncomeServer must be embedded to have forward compatible implementations.
type UnimplementedIncomeServer struct {
}

func (UnimplementedIncomeServer) CreateIncome(context.Context, *CreateIncomeRequest) (*CreateIncomeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIncome not implemented")
}
func (UnimplementedIncomeServer) GetIncomeList(context.Context, *GetIncomeListRequest) (*GetIncomeListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIncomeList not implemented")
}
func (UnimplementedIncomeServer) GetTotalIncome(context.Context, *GetTotalIncomeRequest) (*GetTotalIncomeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTotalIncome not implemented")
}
func (UnimplementedIncomeServer) ApplyWithdrawal(context.Context, *ApplyWithdrawalRequest) (*ApplyWithdrawalReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyWithdrawal not implemented")
}
func (UnimplementedIncomeServer) GetWithdrawalList(context.Context, *GetWithdrawalListRequest) (*GetWithdrawalListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWithdrawalList not implemented")
}
func (UnimplementedIncomeServer) UpdateWithdrawalStatus(context.Context, *UpdateWithdrawalStatusRequest) (*UpdateWithdrawalStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWithdrawalStatus not implemented")
}
func (UnimplementedIncomeServer) mustEmbedUnimplementedIncomeServer() {}

// UnsafeIncomeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncomeServer will
// result in compilation errors.
type UnsafeIncomeServer interface {
	mustEmbedUnimplementedIncomeServer()
}

func RegisterIncomeServer(s grpc.ServiceRegistrar, srv IncomeServer) {
	s.RegisterService(&Income_ServiceDesc, srv)
}

func _Income_CreateIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).CreateIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_CreateIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).CreateIncome(ctx, req.(*CreateIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Income_GetIncomeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).GetIncomeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_GetIncomeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).GetIncomeList(ctx, req.(*GetIncomeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Income_GetTotalIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTotalIncomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).GetTotalIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_GetTotalIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).GetTotalIncome(ctx, req.(*GetTotalIncomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Income_ApplyWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).ApplyWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_ApplyWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).ApplyWithdrawal(ctx, req.(*ApplyWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Income_GetWithdrawalList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawalListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).GetWithdrawalList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_GetWithdrawalList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).GetWithdrawalList(ctx, req.(*GetWithdrawalListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Income_UpdateWithdrawalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWithdrawalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncomeServer).UpdateWithdrawalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Income_UpdateWithdrawalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncomeServer).UpdateWithdrawalStatus(ctx, req.(*UpdateWithdrawalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Income_ServiceDesc is the grpc.ServiceDesc for Income service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Income_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Income",
	HandlerType: (*IncomeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIncome",
			Handler:    _Income_CreateIncome_Handler,
		},
		{
			MethodName: "GetIncomeList",
			Handler:    _Income_GetIncomeList_Handler,
		},
		{
			MethodName: "GetTotalIncome",
			Handler:    _Income_GetTotalIncome_Handler,
		},
		{
			MethodName: "ApplyWithdrawal",
			Handler:    _Income_ApplyWithdrawal_Handler,
		},
		{
			MethodName: "GetWithdrawalList",
			Handler:    _Income_GetWithdrawalList_Handler,
		},
		{
			MethodName: "UpdateWithdrawalStatus",
			Handler:    _Income_UpdateWithdrawalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/income.proto",
}
