// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: api/rider/v1/location.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationLocationGetLocation = "/api.rider.v1.Location/GetLocation"
const OperationLocationGetNearbyRiders = "/api.rider.v1.Location/GetNearbyRiders"
const OperationLocationUpdateLocation = "/api.rider.v1.Location/UpdateLocation"

type LocationHTTPServer interface {
	// GetLocation 获取骑手位置
	GetLocation(context.Context, *GetLocationRequest) (*GetLocationReply, error)
	// GetNearbyRiders 获取附近骑手位置
	GetNearbyRiders(context.Context, *GetNearbyRidersRequest) (*GetNearbyRidersReply, error)
	// UpdateLocation 上报骑手位置
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationReply, error)
}

func RegisterLocationHTTPServer(s *http.Server, srv LocationHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/location", _Location_UpdateLocation0_HTTP_Handler(srv))
	r.GET("/rider/v1/location/{rider_id}", _Location_GetLocation0_HTTP_Handler(srv))
	r.GET("/rider/v1/nearby_riders", _Location_GetNearbyRiders0_HTTP_Handler(srv))
}

func _Location_UpdateLocation0_HTTP_Handler(srv LocationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateLocationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLocationUpdateLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateLocation(ctx, req.(*UpdateLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateLocationReply)
		return ctx.Result(200, reply)
	}
}

func _Location_GetLocation0_HTTP_Handler(srv LocationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetLocationRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLocationGetLocation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetLocation(ctx, req.(*GetLocationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetLocationReply)
		return ctx.Result(200, reply)
	}
}

func _Location_GetNearbyRiders0_HTTP_Handler(srv LocationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNearbyRidersRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationLocationGetNearbyRiders)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNearbyRiders(ctx, req.(*GetNearbyRidersRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetNearbyRidersReply)
		return ctx.Result(200, reply)
	}
}

type LocationHTTPClient interface {
	// GetLocation 获取骑手位置
	GetLocation(ctx context.Context, req *GetLocationRequest, opts ...http.CallOption) (rsp *GetLocationReply, err error)
	// GetNearbyRiders 获取附近骑手位置
	GetNearbyRiders(ctx context.Context, req *GetNearbyRidersRequest, opts ...http.CallOption) (rsp *GetNearbyRidersReply, err error)
	// UpdateLocation 上报骑手位置
	UpdateLocation(ctx context.Context, req *UpdateLocationRequest, opts ...http.CallOption) (rsp *UpdateLocationReply, err error)
}

type LocationHTTPClientImpl struct {
	cc *http.Client
}

func NewLocationHTTPClient(client *http.Client) LocationHTTPClient {
	return &LocationHTTPClientImpl{client}
}

// GetLocation 获取骑手位置
func (c *LocationHTTPClientImpl) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...http.CallOption) (*GetLocationReply, error) {
	var out GetLocationReply
	pattern := "/rider/v1/location/{rider_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLocationGetLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetNearbyRiders 获取附近骑手位置
func (c *LocationHTTPClientImpl) GetNearbyRiders(ctx context.Context, in *GetNearbyRidersRequest, opts ...http.CallOption) (*GetNearbyRidersReply, error) {
	var out GetNearbyRidersReply
	pattern := "/rider/v1/nearby_riders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationLocationGetNearbyRiders))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateLocation 上报骑手位置
func (c *LocationHTTPClientImpl) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...http.CallOption) (*UpdateLocationReply, error) {
	var out UpdateLocationReply
	pattern := "/rider/v1/location"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationLocationUpdateLocation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
