// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/message.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Message_SendMessage_FullMethodName            = "/api.rider.v1.Message/SendMessage"
	Message_GetMessageList_FullMethodName         = "/api.rider.v1.Message/GetMessageList"
	Message_GetUnreadMessageCount_FullMethodName  = "/api.rider.v1.Message/GetUnreadMessageCount"
	Message_MarkMessageAsRead_FullMethodName      = "/api.rider.v1.Message/MarkMessageAsRead"
	Message_SubscribeMessages_FullMethodName      = "/api.rider.v1.Message/SubscribeMessages"
	Message_CreateGroup_FullMethodName            = "/api.rider.v1.Message/CreateGroup"
	Message_JoinGroup_FullMethodName              = "/api.rider.v1.Message/JoinGroup"
	Message_LeaveGroup_FullMethodName             = "/api.rider.v1.Message/LeaveGroup"
	Message_GetGroupList_FullMethodName           = "/api.rider.v1.Message/GetGroupList"
	Message_GetGroupMembers_FullMethodName        = "/api.rider.v1.Message/GetGroupMembers"
	Message_SendGroupMessage_FullMethodName       = "/api.rider.v1.Message/SendGroupMessage"
	Message_GetGroupMessageList_FullMethodName    = "/api.rider.v1.Message/GetGroupMessageList"
	Message_SubscribeGroupMessages_FullMethodName = "/api.rider.v1.Message/SubscribeGroupMessages"
)

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 消息服务
type MessageClient interface {
	// 发送消息
	SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error)
	// 获取消息列表
	GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListReply, error)
	// 获取未读消息数量
	GetUnreadMessageCount(ctx context.Context, in *GetUnreadMessageCountRequest, opts ...grpc.CallOption) (*GetUnreadMessageCountReply, error)
	// 标记消息为已读
	MarkMessageAsRead(ctx context.Context, in *MarkMessageAsReadRequest, opts ...grpc.CallOption) (*MarkMessageAsReadReply, error)
	// 实时消息推送（WebSocket）
	SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (Message_SubscribeMessagesClient, error)
	// 创建群组
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error)
	// 加入群组
	JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupReply, error)
	// 退出群组
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupReply, error)
	// 获取群组列表
	GetGroupList(ctx context.Context, in *GetGroupListRequest, opts ...grpc.CallOption) (*GetGroupListReply, error)
	// 获取群组成员列表
	GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersReply, error)
	// 发送群聊消息
	SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageReply, error)
	// 获取群聊消息列表
	GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*GetGroupMessageListReply, error)
	// 实时群聊消息推送（WebSocket）
	SubscribeGroupMessages(ctx context.Context, in *SubscribeGroupMessagesRequest, opts ...grpc.CallOption) (Message_SubscribeGroupMessagesClient, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMessageReply)
	err := c.cc.Invoke(ctx, Message_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetMessageList(ctx context.Context, in *GetMessageListRequest, opts ...grpc.CallOption) (*GetMessageListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageListReply)
	err := c.cc.Invoke(ctx, Message_GetMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetUnreadMessageCount(ctx context.Context, in *GetUnreadMessageCountRequest, opts ...grpc.CallOption) (*GetUnreadMessageCountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadMessageCountReply)
	err := c.cc.Invoke(ctx, Message_GetUnreadMessageCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) MarkMessageAsRead(ctx context.Context, in *MarkMessageAsReadRequest, opts ...grpc.CallOption) (*MarkMessageAsReadReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkMessageAsReadReply)
	err := c.cc.Invoke(ctx, Message_MarkMessageAsRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SubscribeMessages(ctx context.Context, in *SubscribeMessagesRequest, opts ...grpc.CallOption) (Message_SubscribeMessagesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[0], Message_SubscribeMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &messageSubscribeMessagesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Message_SubscribeMessagesClient interface {
	Recv() (*SubscribeMessagesReply, error)
	grpc.ClientStream
}

type messageSubscribeMessagesClient struct {
	grpc.ClientStream
}

func (x *messageSubscribeMessagesClient) Recv() (*SubscribeMessagesReply, error) {
	m := new(SubscribeMessagesReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *messageClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupReply)
	err := c.cc.Invoke(ctx, Message_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupReply)
	err := c.cc.Invoke(ctx, Message_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupReply)
	err := c.cc.Invoke(ctx, Message_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGroupList(ctx context.Context, in *GetGroupListRequest, opts ...grpc.CallOption) (*GetGroupListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupListReply)
	err := c.cc.Invoke(ctx, Message_GetGroupList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersRequest, opts ...grpc.CallOption) (*GetGroupMembersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersReply)
	err := c.cc.Invoke(ctx, Message_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendGroupMessageReply)
	err := c.cc.Invoke(ctx, Message_SendGroupMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) GetGroupMessageList(ctx context.Context, in *GetGroupMessageListRequest, opts ...grpc.CallOption) (*GetGroupMessageListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMessageListReply)
	err := c.cc.Invoke(ctx, Message_GetGroupMessageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) SubscribeGroupMessages(ctx context.Context, in *SubscribeGroupMessagesRequest, opts ...grpc.CallOption) (Message_SubscribeGroupMessagesClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Message_ServiceDesc.Streams[1], Message_SubscribeGroupMessages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &messageSubscribeGroupMessagesClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Message_SubscribeGroupMessagesClient interface {
	Recv() (*SubscribeGroupMessagesReply, error)
	grpc.ClientStream
}

type messageSubscribeGroupMessagesClient struct {
	grpc.ClientStream
}

func (x *messageSubscribeGroupMessagesClient) Recv() (*SubscribeGroupMessagesReply, error) {
	m := new(SubscribeGroupMessagesReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MessageServer is the server API for Message service.
// All implementations must embed UnimplementedMessageServer
// for forward compatibility
//
// 消息服务
type MessageServer interface {
	// 发送消息
	SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error)
	// 获取消息列表
	GetMessageList(context.Context, *GetMessageListRequest) (*GetMessageListReply, error)
	// 获取未读消息数量
	GetUnreadMessageCount(context.Context, *GetUnreadMessageCountRequest) (*GetUnreadMessageCountReply, error)
	// 标记消息为已读
	MarkMessageAsRead(context.Context, *MarkMessageAsReadRequest) (*MarkMessageAsReadReply, error)
	// 实时消息推送（WebSocket）
	SubscribeMessages(*SubscribeMessagesRequest, Message_SubscribeMessagesServer) error
	// 创建群组
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupReply, error)
	// 加入群组
	JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupReply, error)
	// 退出群组
	LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupReply, error)
	// 获取群组列表
	GetGroupList(context.Context, *GetGroupListRequest) (*GetGroupListReply, error)
	// 获取群组成员列表
	GetGroupMembers(context.Context, *GetGroupMembersRequest) (*GetGroupMembersReply, error)
	// 发送群聊消息
	SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageReply, error)
	// 获取群聊消息列表
	GetGroupMessageList(context.Context, *GetGroupMessageListRequest) (*GetGroupMessageListReply, error)
	// 实时群聊消息推送（WebSocket）
	SubscribeGroupMessages(*SubscribeGroupMessagesRequest, Message_SubscribeGroupMessagesServer) error
	mustEmbedUnimplementedMessageServer()
}

// UnimplementedMessageServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (UnimplementedMessageServer) SendMessage(context.Context, *SendMessageRequest) (*SendMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMessageServer) GetMessageList(context.Context, *GetMessageListRequest) (*GetMessageListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMessageList not implemented")
}
func (UnimplementedMessageServer) GetUnreadMessageCount(context.Context, *GetUnreadMessageCountRequest) (*GetUnreadMessageCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadMessageCount not implemented")
}
func (UnimplementedMessageServer) MarkMessageAsRead(context.Context, *MarkMessageAsReadRequest) (*MarkMessageAsReadReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkMessageAsRead not implemented")
}
func (UnimplementedMessageServer) SubscribeMessages(*SubscribeMessagesRequest, Message_SubscribeMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMessages not implemented")
}
func (UnimplementedMessageServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedMessageServer) JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedMessageServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedMessageServer) GetGroupList(context.Context, *GetGroupListRequest) (*GetGroupListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupList not implemented")
}
func (UnimplementedMessageServer) GetGroupMembers(context.Context, *GetGroupMembersRequest) (*GetGroupMembersReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedMessageServer) SendGroupMessage(context.Context, *SendGroupMessageRequest) (*SendGroupMessageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendGroupMessage not implemented")
}
func (UnimplementedMessageServer) GetGroupMessageList(context.Context, *GetGroupMessageListRequest) (*GetGroupMessageListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGroupMessageList not implemented")
}
func (UnimplementedMessageServer) SubscribeGroupMessages(*SubscribeGroupMessagesRequest, Message_SubscribeGroupMessagesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeGroupMessages not implemented")
}
func (UnimplementedMessageServer) mustEmbedUnimplementedMessageServer() {}

// UnsafeMessageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServer will
// result in compilation errors.
type UnsafeMessageServer interface {
	mustEmbedUnimplementedMessageServer()
}

func RegisterMessageServer(s grpc.ServiceRegistrar, srv MessageServer) {
	s.RegisterService(&Message_ServiceDesc, srv)
}

func _Message_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendMessage(ctx, req.(*SendMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetMessageList(ctx, req.(*GetMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetUnreadMessageCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadMessageCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetUnreadMessageCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetUnreadMessageCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetUnreadMessageCount(ctx, req.(*GetUnreadMessageCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_MarkMessageAsRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkMessageAsReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).MarkMessageAsRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_MarkMessageAsRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).MarkMessageAsRead(ctx, req.(*MarkMessageAsReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SubscribeMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServer).SubscribeMessages(m, &messageSubscribeMessagesServer{ServerStream: stream})
}

type Message_SubscribeMessagesServer interface {
	Send(*SubscribeMessagesReply) error
	grpc.ServerStream
}

type messageSubscribeMessagesServer struct {
	grpc.ServerStream
}

func (x *messageSubscribeMessagesServer) Send(m *SubscribeMessagesReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Message_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).JoinGroup(ctx, req.(*JoinGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGroupList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGroupList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetGroupList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGroupList(ctx, req.(*GetGroupListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGroupMembers(ctx, req.(*GetGroupMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SendGroupMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGroupMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).SendGroupMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_SendGroupMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).SendGroupMessage(ctx, req.(*SendGroupMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_GetGroupMessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMessageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).GetGroupMessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Message_GetGroupMessageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).GetGroupMessageList(ctx, req.(*GetGroupMessageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_SubscribeGroupMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeGroupMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MessageServer).SubscribeGroupMessages(m, &messageSubscribeGroupMessagesServer{ServerStream: stream})
}

type Message_SubscribeGroupMessagesServer interface {
	Send(*SubscribeGroupMessagesReply) error
	grpc.ServerStream
}

type messageSubscribeGroupMessagesServer struct {
	grpc.ServerStream
}

func (x *messageSubscribeGroupMessagesServer) Send(m *SubscribeGroupMessagesReply) error {
	return x.ServerStream.SendMsg(m)
}

// Message_ServiceDesc is the grpc.ServiceDesc for Message service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Message_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _Message_SendMessage_Handler,
		},
		{
			MethodName: "GetMessageList",
			Handler:    _Message_GetMessageList_Handler,
		},
		{
			MethodName: "GetUnreadMessageCount",
			Handler:    _Message_GetUnreadMessageCount_Handler,
		},
		{
			MethodName: "MarkMessageAsRead",
			Handler:    _Message_MarkMessageAsRead_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Message_CreateGroup_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _Message_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _Message_LeaveGroup_Handler,
		},
		{
			MethodName: "GetGroupList",
			Handler:    _Message_GetGroupList_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _Message_GetGroupMembers_Handler,
		},
		{
			MethodName: "SendGroupMessage",
			Handler:    _Message_SendGroupMessage_Handler,
		},
		{
			MethodName: "GetGroupMessageList",
			Handler:    _Message_GetGroupMessageList_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeMessages",
			Handler:       _Message_SubscribeMessages_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeGroupMessages",
			Handler:       _Message_SubscribeGroupMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rider/v1/message.proto",
}
