// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/qualification.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationQualificationGetVerificationDetail = "/api.rider.v1.Qualification/GetVerificationDetail"
const OperationQualificationGetVerificationStatus = "/api.rider.v1.Qualification/GetVerificationStatus"
const OperationQualificationResubmitVerification = "/api.rider.v1.Qualification/ResubmitVerification"
const OperationQualificationSubmitDriverLicense = "/api.rider.v1.Qualification/SubmitDriverLicense"
const OperationQualificationSubmitHealthCertificate = "/api.rider.v1.Qualification/SubmitHealthCertificate"
const OperationQualificationSubmitIDCard = "/api.rider.v1.Qualification/SubmitIDCard"
const OperationQualificationVerifyQualification = "/api.rider.v1.Qualification/VerifyQualification"

type QualificationHTTPServer interface {
	// GetVerificationDetail 获取验证详情
	GetVerificationDetail(context.Context, *GetVerificationDetailRequest) (*GetVerificationDetailReply, error)
	// GetVerificationStatus 获取验证状态
	GetVerificationStatus(context.Context, *GetVerificationStatusRequest) (*GetVerificationStatusReply, error)
	// ResubmitVerification 重新提交验证材料
	ResubmitVerification(context.Context, *ResubmitVerificationRequest) (*ResubmitVerificationReply, error)
	// SubmitDriverLicense 提交驾驶证信息
	SubmitDriverLicense(context.Context, *SubmitDriverLicenseRequest) (*SubmitDriverLicenseReply, error)
	// SubmitHealthCertificate 提交健康证信息
	SubmitHealthCertificate(context.Context, *SubmitHealthCertificateRequest) (*SubmitHealthCertificateReply, error)
	// SubmitIDCard 提交身份证信息
	SubmitIDCard(context.Context, *SubmitIDCardRequest) (*SubmitIDCardReply, error)
	// VerifyQualification 审核验证（管理员接口）
	VerifyQualification(context.Context, *VerifyQualificationRequest) (*VerifyQualificationReply, error)
}

func RegisterQualificationHTTPServer(s *http.Server, srv QualificationHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/qualification/idcard", _Qualification_SubmitIDCard0_HTTP_Handler(srv))
	r.POST("/rider/v1/qualification/driver-license", _Qualification_SubmitDriverLicense0_HTTP_Handler(srv))
	r.POST("/rider/v1/qualification/health", _Qualification_SubmitHealthCertificate0_HTTP_Handler(srv))
	r.GET("/rider/v1/qualification/status", _Qualification_GetVerificationStatus0_HTTP_Handler(srv))
	r.GET("/rider/v1/qualification/detail", _Qualification_GetVerificationDetail0_HTTP_Handler(srv))
	r.POST("/rider/v1/qualification/resubmit", _Qualification_ResubmitVerification0_HTTP_Handler(srv))
	r.POST("/rider/v1/qualification/verify", _Qualification_VerifyQualification0_HTTP_Handler(srv))
}

func _Qualification_SubmitIDCard0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitIDCardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationSubmitIDCard)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitIDCard(ctx, req.(*SubmitIDCardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitIDCardReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_SubmitDriverLicense0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitDriverLicenseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationSubmitDriverLicense)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitDriverLicense(ctx, req.(*SubmitDriverLicenseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitDriverLicenseReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_SubmitHealthCertificate0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitHealthCertificateRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationSubmitHealthCertificate)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitHealthCertificate(ctx, req.(*SubmitHealthCertificateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitHealthCertificateReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_GetVerificationStatus0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVerificationStatusRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationGetVerificationStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVerificationStatus(ctx, req.(*GetVerificationStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetVerificationStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_GetVerificationDetail0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetVerificationDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationGetVerificationDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetVerificationDetail(ctx, req.(*GetVerificationDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetVerificationDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_ResubmitVerification0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ResubmitVerificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationResubmitVerification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ResubmitVerification(ctx, req.(*ResubmitVerificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ResubmitVerificationReply)
		return ctx.Result(200, reply)
	}
}

func _Qualification_VerifyQualification0_HTTP_Handler(srv QualificationHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in VerifyQualificationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationQualificationVerifyQualification)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.VerifyQualification(ctx, req.(*VerifyQualificationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*VerifyQualificationReply)
		return ctx.Result(200, reply)
	}
}

type QualificationHTTPClient interface {
	// GetVerificationDetail 获取验证详情
	GetVerificationDetail(ctx context.Context, req *GetVerificationDetailRequest, opts ...http.CallOption) (rsp *GetVerificationDetailReply, err error)
	// GetVerificationStatus 获取验证状态
	GetVerificationStatus(ctx context.Context, req *GetVerificationStatusRequest, opts ...http.CallOption) (rsp *GetVerificationStatusReply, err error)
	// ResubmitVerification 重新提交验证材料
	ResubmitVerification(ctx context.Context, req *ResubmitVerificationRequest, opts ...http.CallOption) (rsp *ResubmitVerificationReply, err error)
	// SubmitDriverLicense 提交驾驶证信息
	SubmitDriverLicense(ctx context.Context, req *SubmitDriverLicenseRequest, opts ...http.CallOption) (rsp *SubmitDriverLicenseReply, err error)
	// SubmitHealthCertificate 提交健康证信息
	SubmitHealthCertificate(ctx context.Context, req *SubmitHealthCertificateRequest, opts ...http.CallOption) (rsp *SubmitHealthCertificateReply, err error)
	// SubmitIDCard 提交身份证信息
	SubmitIDCard(ctx context.Context, req *SubmitIDCardRequest, opts ...http.CallOption) (rsp *SubmitIDCardReply, err error)
	// VerifyQualification 审核验证（管理员接口）
	VerifyQualification(ctx context.Context, req *VerifyQualificationRequest, opts ...http.CallOption) (rsp *VerifyQualificationReply, err error)
}

type QualificationHTTPClientImpl struct {
	cc *http.Client
}

func NewQualificationHTTPClient(client *http.Client) QualificationHTTPClient {
	return &QualificationHTTPClientImpl{client}
}

// GetVerificationDetail 获取验证详情
func (c *QualificationHTTPClientImpl) GetVerificationDetail(ctx context.Context, in *GetVerificationDetailRequest, opts ...http.CallOption) (*GetVerificationDetailReply, error) {
	var out GetVerificationDetailReply
	pattern := "/rider/v1/qualification/detail"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationQualificationGetVerificationDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetVerificationStatus 获取验证状态
func (c *QualificationHTTPClientImpl) GetVerificationStatus(ctx context.Context, in *GetVerificationStatusRequest, opts ...http.CallOption) (*GetVerificationStatusReply, error) {
	var out GetVerificationStatusReply
	pattern := "/rider/v1/qualification/status"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationQualificationGetVerificationStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ResubmitVerification 重新提交验证材料
func (c *QualificationHTTPClientImpl) ResubmitVerification(ctx context.Context, in *ResubmitVerificationRequest, opts ...http.CallOption) (*ResubmitVerificationReply, error) {
	var out ResubmitVerificationReply
	pattern := "/rider/v1/qualification/resubmit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQualificationResubmitVerification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitDriverLicense 提交驾驶证信息
func (c *QualificationHTTPClientImpl) SubmitDriverLicense(ctx context.Context, in *SubmitDriverLicenseRequest, opts ...http.CallOption) (*SubmitDriverLicenseReply, error) {
	var out SubmitDriverLicenseReply
	pattern := "/rider/v1/qualification/driver-license"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQualificationSubmitDriverLicense))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitHealthCertificate 提交健康证信息
func (c *QualificationHTTPClientImpl) SubmitHealthCertificate(ctx context.Context, in *SubmitHealthCertificateRequest, opts ...http.CallOption) (*SubmitHealthCertificateReply, error) {
	var out SubmitHealthCertificateReply
	pattern := "/rider/v1/qualification/health"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQualificationSubmitHealthCertificate))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitIDCard 提交身份证信息
func (c *QualificationHTTPClientImpl) SubmitIDCard(ctx context.Context, in *SubmitIDCardRequest, opts ...http.CallOption) (*SubmitIDCardReply, error) {
	var out SubmitIDCardReply
	pattern := "/rider/v1/qualification/idcard"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQualificationSubmitIDCard))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// VerifyQualification 审核验证（管理员接口）
func (c *QualificationHTTPClientImpl) VerifyQualification(ctx context.Context, in *VerifyQualificationRequest, opts ...http.CallOption) (*VerifyQualificationReply, error) {
	var out VerifyQualificationReply
	pattern := "/rider/v1/qualification/verify"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationQualificationVerifyQualification))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
