// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/qualification.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Qualification_SubmitIDCard_FullMethodName            = "/api.rider.v1.Qualification/SubmitIDCard"
	Qualification_SubmitDriverLicense_FullMethodName     = "/api.rider.v1.Qualification/SubmitDriverLicense"
	Qualification_SubmitHealthCertificate_FullMethodName = "/api.rider.v1.Qualification/SubmitHealthCertificate"
	Qualification_GetVerificationStatus_FullMethodName   = "/api.rider.v1.Qualification/GetVerificationStatus"
	Qualification_GetVerificationDetail_FullMethodName   = "/api.rider.v1.Qualification/GetVerificationDetail"
	Qualification_ResubmitVerification_FullMethodName    = "/api.rider.v1.Qualification/ResubmitVerification"
	Qualification_VerifyQualification_FullMethodName     = "/api.rider.v1.Qualification/VerifyQualification"
)

// QualificationClient is the client API for Qualification service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 骑手资质验证服务
type QualificationClient interface {
	// 提交身份证信息
	SubmitIDCard(ctx context.Context, in *SubmitIDCardRequest, opts ...grpc.CallOption) (*SubmitIDCardReply, error)
	// 提交驾驶证信息
	SubmitDriverLicense(ctx context.Context, in *SubmitDriverLicenseRequest, opts ...grpc.CallOption) (*SubmitDriverLicenseReply, error)
	// 提交健康证信息
	SubmitHealthCertificate(ctx context.Context, in *SubmitHealthCertificateRequest, opts ...grpc.CallOption) (*SubmitHealthCertificateReply, error)
	// 获取验证状态
	GetVerificationStatus(ctx context.Context, in *GetVerificationStatusRequest, opts ...grpc.CallOption) (*GetVerificationStatusReply, error)
	// 获取验证详情
	GetVerificationDetail(ctx context.Context, in *GetVerificationDetailRequest, opts ...grpc.CallOption) (*GetVerificationDetailReply, error)
	// 重新提交验证材料
	ResubmitVerification(ctx context.Context, in *ResubmitVerificationRequest, opts ...grpc.CallOption) (*ResubmitVerificationReply, error)
	// 审核验证（管理员接口）
	VerifyQualification(ctx context.Context, in *VerifyQualificationRequest, opts ...grpc.CallOption) (*VerifyQualificationReply, error)
}

type qualificationClient struct {
	cc grpc.ClientConnInterface
}

func NewQualificationClient(cc grpc.ClientConnInterface) QualificationClient {
	return &qualificationClient{cc}
}

func (c *qualificationClient) SubmitIDCard(ctx context.Context, in *SubmitIDCardRequest, opts ...grpc.CallOption) (*SubmitIDCardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitIDCardReply)
	err := c.cc.Invoke(ctx, Qualification_SubmitIDCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) SubmitDriverLicense(ctx context.Context, in *SubmitDriverLicenseRequest, opts ...grpc.CallOption) (*SubmitDriverLicenseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitDriverLicenseReply)
	err := c.cc.Invoke(ctx, Qualification_SubmitDriverLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) SubmitHealthCertificate(ctx context.Context, in *SubmitHealthCertificateRequest, opts ...grpc.CallOption) (*SubmitHealthCertificateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitHealthCertificateReply)
	err := c.cc.Invoke(ctx, Qualification_SubmitHealthCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) GetVerificationStatus(ctx context.Context, in *GetVerificationStatusRequest, opts ...grpc.CallOption) (*GetVerificationStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerificationStatusReply)
	err := c.cc.Invoke(ctx, Qualification_GetVerificationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) GetVerificationDetail(ctx context.Context, in *GetVerificationDetailRequest, opts ...grpc.CallOption) (*GetVerificationDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVerificationDetailReply)
	err := c.cc.Invoke(ctx, Qualification_GetVerificationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) ResubmitVerification(ctx context.Context, in *ResubmitVerificationRequest, opts ...grpc.CallOption) (*ResubmitVerificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResubmitVerificationReply)
	err := c.cc.Invoke(ctx, Qualification_ResubmitVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qualificationClient) VerifyQualification(ctx context.Context, in *VerifyQualificationRequest, opts ...grpc.CallOption) (*VerifyQualificationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyQualificationReply)
	err := c.cc.Invoke(ctx, Qualification_VerifyQualification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QualificationServer is the server API for Qualification service.
// All implementations must embed UnimplementedQualificationServer
// for forward compatibility
//
// 骑手资质验证服务
type QualificationServer interface {
	// 提交身份证信息
	SubmitIDCard(context.Context, *SubmitIDCardRequest) (*SubmitIDCardReply, error)
	// 提交驾驶证信息
	SubmitDriverLicense(context.Context, *SubmitDriverLicenseRequest) (*SubmitDriverLicenseReply, error)
	// 提交健康证信息
	SubmitHealthCertificate(context.Context, *SubmitHealthCertificateRequest) (*SubmitHealthCertificateReply, error)
	// 获取验证状态
	GetVerificationStatus(context.Context, *GetVerificationStatusRequest) (*GetVerificationStatusReply, error)
	// 获取验证详情
	GetVerificationDetail(context.Context, *GetVerificationDetailRequest) (*GetVerificationDetailReply, error)
	// 重新提交验证材料
	ResubmitVerification(context.Context, *ResubmitVerificationRequest) (*ResubmitVerificationReply, error)
	// 审核验证（管理员接口）
	VerifyQualification(context.Context, *VerifyQualificationRequest) (*VerifyQualificationReply, error)
	mustEmbedUnimplementedQualificationServer()
}

// UnimplementedQualificationServer must be embedded to have forward compatible implementations.
type UnimplementedQualificationServer struct {
}

func (UnimplementedQualificationServer) SubmitIDCard(context.Context, *SubmitIDCardRequest) (*SubmitIDCardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitIDCard not implemented")
}
func (UnimplementedQualificationServer) SubmitDriverLicense(context.Context, *SubmitDriverLicenseRequest) (*SubmitDriverLicenseReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitDriverLicense not implemented")
}
func (UnimplementedQualificationServer) SubmitHealthCertificate(context.Context, *SubmitHealthCertificateRequest) (*SubmitHealthCertificateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitHealthCertificate not implemented")
}
func (UnimplementedQualificationServer) GetVerificationStatus(context.Context, *GetVerificationStatusRequest) (*GetVerificationStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationStatus not implemented")
}
func (UnimplementedQualificationServer) GetVerificationDetail(context.Context, *GetVerificationDetailRequest) (*GetVerificationDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVerificationDetail not implemented")
}
func (UnimplementedQualificationServer) ResubmitVerification(context.Context, *ResubmitVerificationRequest) (*ResubmitVerificationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResubmitVerification not implemented")
}
func (UnimplementedQualificationServer) VerifyQualification(context.Context, *VerifyQualificationRequest) (*VerifyQualificationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyQualification not implemented")
}
func (UnimplementedQualificationServer) mustEmbedUnimplementedQualificationServer() {}

// UnsafeQualificationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QualificationServer will
// result in compilation errors.
type UnsafeQualificationServer interface {
	mustEmbedUnimplementedQualificationServer()
}

func RegisterQualificationServer(s grpc.ServiceRegistrar, srv QualificationServer) {
	s.RegisterService(&Qualification_ServiceDesc, srv)
}

func _Qualification_SubmitIDCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitIDCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).SubmitIDCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_SubmitIDCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).SubmitIDCard(ctx, req.(*SubmitIDCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_SubmitDriverLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitDriverLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).SubmitDriverLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_SubmitDriverLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).SubmitDriverLicense(ctx, req.(*SubmitDriverLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_SubmitHealthCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitHealthCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).SubmitHealthCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_SubmitHealthCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).SubmitHealthCertificate(ctx, req.(*SubmitHealthCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_GetVerificationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).GetVerificationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_GetVerificationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).GetVerificationStatus(ctx, req.(*GetVerificationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_GetVerificationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVerificationDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).GetVerificationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_GetVerificationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).GetVerificationDetail(ctx, req.(*GetVerificationDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_ResubmitVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResubmitVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).ResubmitVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_ResubmitVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).ResubmitVerification(ctx, req.(*ResubmitVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qualification_VerifyQualification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyQualificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QualificationServer).VerifyQualification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Qualification_VerifyQualification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QualificationServer).VerifyQualification(ctx, req.(*VerifyQualificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Qualification_ServiceDesc is the grpc.ServiceDesc for Qualification service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Qualification_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Qualification",
	HandlerType: (*QualificationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitIDCard",
			Handler:    _Qualification_SubmitIDCard_Handler,
		},
		{
			MethodName: "SubmitDriverLicense",
			Handler:    _Qualification_SubmitDriverLicense_Handler,
		},
		{
			MethodName: "SubmitHealthCertificate",
			Handler:    _Qualification_SubmitHealthCertificate_Handler,
		},
		{
			MethodName: "GetVerificationStatus",
			Handler:    _Qualification_GetVerificationStatus_Handler,
		},
		{
			MethodName: "GetVerificationDetail",
			Handler:    _Qualification_GetVerificationDetail_Handler,
		},
		{
			MethodName: "ResubmitVerification",
			Handler:    _Qualification_ResubmitVerification_Handler,
		},
		{
			MethodName: "VerifyQualification",
			Handler:    _Qualification_VerifyQualification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/qualification.proto",
}
