// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: api/rider/v1/rating.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRatingGetComplaints = "/api.rider.v1.Rating/GetComplaints"
const OperationRatingGetRiderRatingStats = "/api.rider.v1.Rating/GetRiderRatingStats"
const OperationRatingGetRiderRatings = "/api.rider.v1.Rating/GetRiderRatings"
const OperationRatingSubmitComplaint = "/api.rider.v1.Rating/SubmitComplaint"
const OperationRatingSubmitOrderRating = "/api.rider.v1.Rating/SubmitOrderRating"

type RatingHTTPServer interface {
	// GetComplaints 获取投诉列表
	GetComplaints(context.Context, *GetComplaintsRequest) (*GetComplaintsReply, error)
	// GetRiderRatingStats 获取骑手评分统计
	GetRiderRatingStats(context.Context, *GetRiderRatingStatsRequest) (*GetRiderRatingStatsReply, error)
	// GetRiderRatings 获取骑手评价列表
	GetRiderRatings(context.Context, *GetRiderRatingsRequest) (*GetRiderRatingsReply, error)
	// SubmitComplaint 提交投诉
	SubmitComplaint(context.Context, *SubmitComplaintRequest) (*SubmitComplaintReply, error)
	// SubmitOrderRating 提交订单评价
	SubmitOrderRating(context.Context, *SubmitOrderRatingRequest) (*SubmitOrderRatingReply, error)
}

func RegisterRatingHTTPServer(s *http.Server, srv RatingHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/rating/order", _Rating_SubmitOrderRating0_HTTP_Handler(srv))
	r.GET("/rider/v1/ratings", _Rating_GetRiderRatings0_HTTP_Handler(srv))
	r.GET("/rider/v1/rating/stats", _Rating_GetRiderRatingStats0_HTTP_Handler(srv))
	r.POST("/rider/v1/complaint", _Rating_SubmitComplaint0_HTTP_Handler(srv))
	r.GET("/rider/v1/complaints", _Rating_GetComplaints0_HTTP_Handler(srv))
}

func _Rating_SubmitOrderRating0_HTTP_Handler(srv RatingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitOrderRatingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingSubmitOrderRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitOrderRating(ctx, req.(*SubmitOrderRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitOrderRatingReply)
		return ctx.Result(200, reply)
	}
}

func _Rating_GetRiderRatings0_HTTP_Handler(srv RatingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRiderRatingsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingGetRiderRatings)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRiderRatings(ctx, req.(*GetRiderRatingsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRiderRatingsReply)
		return ctx.Result(200, reply)
	}
}

func _Rating_GetRiderRatingStats0_HTTP_Handler(srv RatingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRiderRatingStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingGetRiderRatingStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRiderRatingStats(ctx, req.(*GetRiderRatingStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRiderRatingStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Rating_SubmitComplaint0_HTTP_Handler(srv RatingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitComplaintRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingSubmitComplaint)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitComplaint(ctx, req.(*SubmitComplaintRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitComplaintReply)
		return ctx.Result(200, reply)
	}
}

func _Rating_GetComplaints0_HTTP_Handler(srv RatingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetComplaintsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingGetComplaints)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetComplaints(ctx, req.(*GetComplaintsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetComplaintsReply)
		return ctx.Result(200, reply)
	}
}

type RatingHTTPClient interface {
	// GetComplaints 获取投诉列表
	GetComplaints(ctx context.Context, req *GetComplaintsRequest, opts ...http.CallOption) (rsp *GetComplaintsReply, err error)
	// GetRiderRatingStats 获取骑手评分统计
	GetRiderRatingStats(ctx context.Context, req *GetRiderRatingStatsRequest, opts ...http.CallOption) (rsp *GetRiderRatingStatsReply, err error)
	// GetRiderRatings 获取骑手评价列表
	GetRiderRatings(ctx context.Context, req *GetRiderRatingsRequest, opts ...http.CallOption) (rsp *GetRiderRatingsReply, err error)
	// SubmitComplaint 提交投诉
	SubmitComplaint(ctx context.Context, req *SubmitComplaintRequest, opts ...http.CallOption) (rsp *SubmitComplaintReply, err error)
	// SubmitOrderRating 提交订单评价
	SubmitOrderRating(ctx context.Context, req *SubmitOrderRatingRequest, opts ...http.CallOption) (rsp *SubmitOrderRatingReply, err error)
}

type RatingHTTPClientImpl struct {
	cc *http.Client
}

func NewRatingHTTPClient(client *http.Client) RatingHTTPClient {
	return &RatingHTTPClientImpl{client}
}

// GetComplaints 获取投诉列表
func (c *RatingHTTPClientImpl) GetComplaints(ctx context.Context, in *GetComplaintsRequest, opts ...http.CallOption) (*GetComplaintsReply, error) {
	var out GetComplaintsReply
	pattern := "/rider/v1/complaints"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingGetComplaints))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRiderRatingStats 获取骑手评分统计
func (c *RatingHTTPClientImpl) GetRiderRatingStats(ctx context.Context, in *GetRiderRatingStatsRequest, opts ...http.CallOption) (*GetRiderRatingStatsReply, error) {
	var out GetRiderRatingStatsReply
	pattern := "/rider/v1/rating/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingGetRiderRatingStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRiderRatings 获取骑手评价列表
func (c *RatingHTTPClientImpl) GetRiderRatings(ctx context.Context, in *GetRiderRatingsRequest, opts ...http.CallOption) (*GetRiderRatingsReply, error) {
	var out GetRiderRatingsReply
	pattern := "/rider/v1/ratings"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingGetRiderRatings))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitComplaint 提交投诉
func (c *RatingHTTPClientImpl) SubmitComplaint(ctx context.Context, in *SubmitComplaintRequest, opts ...http.CallOption) (*SubmitComplaintReply, error) {
	var out SubmitComplaintReply
	pattern := "/rider/v1/complaint"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingSubmitComplaint))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitOrderRating 提交订单评价
func (c *RatingHTTPClientImpl) SubmitOrderRating(ctx context.Context, in *SubmitOrderRatingRequest, opts ...http.CallOption) (*SubmitOrderRatingReply, error) {
	var out SubmitOrderRatingReply
	pattern := "/rider/v1/rating/order"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingSubmitOrderRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
