// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/rating.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRatingServiceGetRatingDetail = "/api.rider.v1.RatingService/GetRatingDetail"
const OperationRatingServiceGetRatingList = "/api.rider.v1.RatingService/GetRatingList"
const OperationRatingServiceGetRatingRecords = "/api.rider.v1.RatingService/GetRatingRecords"
const OperationRatingServiceGetRatingStatistics = "/api.rider.v1.RatingService/GetRatingStatistics"
const OperationRatingServiceGetRatingSummary = "/api.rider.v1.RatingService/GetRatingSummary"
const OperationRatingServiceGetRiderRating = "/api.rider.v1.RatingService/GetRiderRating"
const OperationRatingServiceHideRating = "/api.rider.v1.RatingService/HideRating"
const OperationRatingServiceRecalculateRating = "/api.rider.v1.RatingService/RecalculateRating"
const OperationRatingServiceReplyToRating = "/api.rider.v1.RatingService/ReplyToRating"
const OperationRatingServiceSubmitRating = "/api.rider.v1.RatingService/SubmitRating"

type RatingServiceHTTPServer interface {
	// GetRatingDetail 获取评分详情
	GetRatingDetail(context.Context, *GetRatingDetailRequest) (*GetRatingDetailReply, error)
	// GetRatingList 获取评分列表
	GetRatingList(context.Context, *GetRatingListRequest) (*GetRatingListReply, error)
	// GetRatingRecords 获取评分记录列表
	GetRatingRecords(context.Context, *GetRatingRecordsRequest) (*GetRatingRecordsReply, error)
	// GetRatingStatistics 获取评分统计
	GetRatingStatistics(context.Context, *GetRatingStatisticsRequest) (*GetRatingStatisticsReply, error)
	// GetRatingSummary 获取评分汇总
	GetRatingSummary(context.Context, *GetRatingSummaryRequest) (*GetRatingSummaryReply, error)
	// GetRiderRating 获取骑手评分
	GetRiderRating(context.Context, *GetRiderRatingRequest) (*GetRiderRatingReply, error)
	// HideRating 隐藏评分
	HideRating(context.Context, *HideRatingRequest) (*HideRatingReply, error)
	// RecalculateRating 重新计算评分
	RecalculateRating(context.Context, *RecalculateRatingRequest) (*RecalculateRatingReply, error)
	// ReplyToRating 回复评价
	ReplyToRating(context.Context, *ReplyToRatingRequest) (*ReplyToRatingReply, error)
	// SubmitRating 提交评分
	SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingReply, error)
}

func RegisterRatingServiceHTTPServer(s *http.Server, srv RatingServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/rating/submit", _RatingService_SubmitRating0_HTTP_Handler(srv))
	r.GET("/rider/v1/rating/{rider_id}", _RatingService_GetRiderRating0_HTTP_Handler(srv))
	r.GET("/rider/v1/rating/records", _RatingService_GetRatingRecords0_HTTP_Handler(srv))
	r.GET("/rider/v1/rating/detail/{record_id}", _RatingService_GetRatingDetail0_HTTP_Handler(srv))
	r.POST("/rider/v1/rating/reply", _RatingService_ReplyToRating0_HTTP_Handler(srv))
	r.GET("/rider/v1/rating/summary/{rider_id}", _RatingService_GetRatingSummary0_HTTP_Handler(srv))
	r.GET("/rider/v1/admin/rating/list", _RatingService_GetRatingList0_HTTP_Handler(srv))
	r.POST("/rider/v1/admin/rating/hide", _RatingService_HideRating0_HTTP_Handler(srv))
	r.GET("/rider/v1/admin/rating/statistics", _RatingService_GetRatingStatistics0_HTTP_Handler(srv))
	r.POST("/rider/v1/admin/rating/recalculate", _RatingService_RecalculateRating0_HTTP_Handler(srv))
}

func _RatingService_SubmitRating0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitRatingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceSubmitRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitRating(ctx, req.(*SubmitRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitRatingReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRiderRating0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRiderRatingRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRiderRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRiderRating(ctx, req.(*GetRiderRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRiderRatingReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRatingRecords0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRatingRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingRecords(ctx, req.(*GetRatingRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingRecordsReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRatingDetail0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRatingDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingDetail(ctx, req.(*GetRatingDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingDetailReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_ReplyToRating0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReplyToRatingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceReplyToRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReplyToRating(ctx, req.(*ReplyToRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReplyToRatingReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRatingSummary0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingSummaryRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRatingSummary)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingSummary(ctx, req.(*GetRatingSummaryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingSummaryReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRatingList0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRatingList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingList(ctx, req.(*GetRatingListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingListReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_HideRating0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HideRatingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceHideRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HideRating(ctx, req.(*HideRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HideRatingReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_GetRatingStatistics0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRatingStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceGetRatingStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRatingStatistics(ctx, req.(*GetRatingStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRatingStatisticsReply)
		return ctx.Result(200, reply)
	}
}

func _RatingService_RecalculateRating0_HTTP_Handler(srv RatingServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RecalculateRatingRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRatingServiceRecalculateRating)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RecalculateRating(ctx, req.(*RecalculateRatingRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RecalculateRatingReply)
		return ctx.Result(200, reply)
	}
}

type RatingServiceHTTPClient interface {
	// GetRatingDetail 获取评分详情
	GetRatingDetail(ctx context.Context, req *GetRatingDetailRequest, opts ...http.CallOption) (rsp *GetRatingDetailReply, err error)
	// GetRatingList 获取评分列表
	GetRatingList(ctx context.Context, req *GetRatingListRequest, opts ...http.CallOption) (rsp *GetRatingListReply, err error)
	// GetRatingRecords 获取评分记录列表
	GetRatingRecords(ctx context.Context, req *GetRatingRecordsRequest, opts ...http.CallOption) (rsp *GetRatingRecordsReply, err error)
	// GetRatingStatistics 获取评分统计
	GetRatingStatistics(ctx context.Context, req *GetRatingStatisticsRequest, opts ...http.CallOption) (rsp *GetRatingStatisticsReply, err error)
	// GetRatingSummary 获取评分汇总
	GetRatingSummary(ctx context.Context, req *GetRatingSummaryRequest, opts ...http.CallOption) (rsp *GetRatingSummaryReply, err error)
	// GetRiderRating 获取骑手评分
	GetRiderRating(ctx context.Context, req *GetRiderRatingRequest, opts ...http.CallOption) (rsp *GetRiderRatingReply, err error)
	// HideRating 隐藏评分
	HideRating(ctx context.Context, req *HideRatingRequest, opts ...http.CallOption) (rsp *HideRatingReply, err error)
	// RecalculateRating 重新计算评分
	RecalculateRating(ctx context.Context, req *RecalculateRatingRequest, opts ...http.CallOption) (rsp *RecalculateRatingReply, err error)
	// ReplyToRating 回复评价
	ReplyToRating(ctx context.Context, req *ReplyToRatingRequest, opts ...http.CallOption) (rsp *ReplyToRatingReply, err error)
	// SubmitRating 提交评分
	SubmitRating(ctx context.Context, req *SubmitRatingRequest, opts ...http.CallOption) (rsp *SubmitRatingReply, err error)
}

type RatingServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRatingServiceHTTPClient(client *http.Client) RatingServiceHTTPClient {
	return &RatingServiceHTTPClientImpl{client}
}

// GetRatingDetail 获取评分详情
func (c *RatingServiceHTTPClientImpl) GetRatingDetail(ctx context.Context, in *GetRatingDetailRequest, opts ...http.CallOption) (*GetRatingDetailReply, error) {
	var out GetRatingDetailReply
	pattern := "/rider/v1/rating/detail/{record_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRatingDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRatingList 获取评分列表
func (c *RatingServiceHTTPClientImpl) GetRatingList(ctx context.Context, in *GetRatingListRequest, opts ...http.CallOption) (*GetRatingListReply, error) {
	var out GetRatingListReply
	pattern := "/rider/v1/admin/rating/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRatingList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRatingRecords 获取评分记录列表
func (c *RatingServiceHTTPClientImpl) GetRatingRecords(ctx context.Context, in *GetRatingRecordsRequest, opts ...http.CallOption) (*GetRatingRecordsReply, error) {
	var out GetRatingRecordsReply
	pattern := "/rider/v1/rating/records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRatingRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRatingStatistics 获取评分统计
func (c *RatingServiceHTTPClientImpl) GetRatingStatistics(ctx context.Context, in *GetRatingStatisticsRequest, opts ...http.CallOption) (*GetRatingStatisticsReply, error) {
	var out GetRatingStatisticsReply
	pattern := "/rider/v1/admin/rating/statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRatingStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRatingSummary 获取评分汇总
func (c *RatingServiceHTTPClientImpl) GetRatingSummary(ctx context.Context, in *GetRatingSummaryRequest, opts ...http.CallOption) (*GetRatingSummaryReply, error) {
	var out GetRatingSummaryReply
	pattern := "/rider/v1/rating/summary/{rider_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRatingSummary))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRiderRating 获取骑手评分
func (c *RatingServiceHTTPClientImpl) GetRiderRating(ctx context.Context, in *GetRiderRatingRequest, opts ...http.CallOption) (*GetRiderRatingReply, error) {
	var out GetRiderRatingReply
	pattern := "/rider/v1/rating/{rider_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRatingServiceGetRiderRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// HideRating 隐藏评分
func (c *RatingServiceHTTPClientImpl) HideRating(ctx context.Context, in *HideRatingRequest, opts ...http.CallOption) (*HideRatingReply, error) {
	var out HideRatingReply
	pattern := "/rider/v1/admin/rating/hide"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingServiceHideRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RecalculateRating 重新计算评分
func (c *RatingServiceHTTPClientImpl) RecalculateRating(ctx context.Context, in *RecalculateRatingRequest, opts ...http.CallOption) (*RecalculateRatingReply, error) {
	var out RecalculateRatingReply
	pattern := "/rider/v1/admin/rating/recalculate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingServiceRecalculateRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReplyToRating 回复评价
func (c *RatingServiceHTTPClientImpl) ReplyToRating(ctx context.Context, in *ReplyToRatingRequest, opts ...http.CallOption) (*ReplyToRatingReply, error) {
	var out ReplyToRatingReply
	pattern := "/rider/v1/rating/reply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingServiceReplyToRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitRating 提交评分
func (c *RatingServiceHTTPClientImpl) SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...http.CallOption) (*SubmitRatingReply, error) {
	var out SubmitRatingReply
	pattern := "/rider/v1/rating/submit"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRatingServiceSubmitRating))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
