// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/rating.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RatingService_SubmitRating_FullMethodName        = "/api.rider.v1.RatingService/SubmitRating"
	RatingService_GetRiderRating_FullMethodName      = "/api.rider.v1.RatingService/GetRiderRating"
	RatingService_GetRatingRecords_FullMethodName    = "/api.rider.v1.RatingService/GetRatingRecords"
	RatingService_GetRatingDetail_FullMethodName     = "/api.rider.v1.RatingService/GetRatingDetail"
	RatingService_ReplyToRating_FullMethodName       = "/api.rider.v1.RatingService/ReplyToRating"
	RatingService_GetRatingSummary_FullMethodName    = "/api.rider.v1.RatingService/GetRatingSummary"
	RatingService_GetRatingList_FullMethodName       = "/api.rider.v1.RatingService/GetRatingList"
	RatingService_HideRating_FullMethodName          = "/api.rider.v1.RatingService/HideRating"
	RatingService_GetRatingStatistics_FullMethodName = "/api.rider.v1.RatingService/GetRatingStatistics"
	RatingService_RecalculateRating_FullMethodName   = "/api.rider.v1.RatingService/RecalculateRating"
)

// RatingServiceClient is the client API for RatingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 骑手评分服务
type RatingServiceClient interface {
	// 提交评分
	SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingReply, error)
	// 获取骑手评分
	GetRiderRating(ctx context.Context, in *GetRiderRatingRequest, opts ...grpc.CallOption) (*GetRiderRatingReply, error)
	// 获取评分记录列表
	GetRatingRecords(ctx context.Context, in *GetRatingRecordsRequest, opts ...grpc.CallOption) (*GetRatingRecordsReply, error)
	// 获取评分详情
	GetRatingDetail(ctx context.Context, in *GetRatingDetailRequest, opts ...grpc.CallOption) (*GetRatingDetailReply, error)
	// 回复评价
	ReplyToRating(ctx context.Context, in *ReplyToRatingRequest, opts ...grpc.CallOption) (*ReplyToRatingReply, error)
	// 获取评分汇总
	GetRatingSummary(ctx context.Context, in *GetRatingSummaryRequest, opts ...grpc.CallOption) (*GetRatingSummaryReply, error)
	// 获取评分列表
	GetRatingList(ctx context.Context, in *GetRatingListRequest, opts ...grpc.CallOption) (*GetRatingListReply, error)
	// 隐藏评分
	HideRating(ctx context.Context, in *HideRatingRequest, opts ...grpc.CallOption) (*HideRatingReply, error)
	// 获取评分统计
	GetRatingStatistics(ctx context.Context, in *GetRatingStatisticsRequest, opts ...grpc.CallOption) (*GetRatingStatisticsReply, error)
	// 重新计算评分
	RecalculateRating(ctx context.Context, in *RecalculateRatingRequest, opts ...grpc.CallOption) (*RecalculateRatingReply, error)
}

type ratingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingServiceClient(cc grpc.ClientConnInterface) RatingServiceClient {
	return &ratingServiceClient{cc}
}

func (c *ratingServiceClient) SubmitRating(ctx context.Context, in *SubmitRatingRequest, opts ...grpc.CallOption) (*SubmitRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitRatingReply)
	err := c.cc.Invoke(ctx, RatingService_SubmitRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRiderRating(ctx context.Context, in *GetRiderRatingRequest, opts ...grpc.CallOption) (*GetRiderRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderRatingReply)
	err := c.cc.Invoke(ctx, RatingService_GetRiderRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRatingRecords(ctx context.Context, in *GetRatingRecordsRequest, opts ...grpc.CallOption) (*GetRatingRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingRecordsReply)
	err := c.cc.Invoke(ctx, RatingService_GetRatingRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRatingDetail(ctx context.Context, in *GetRatingDetailRequest, opts ...grpc.CallOption) (*GetRatingDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingDetailReply)
	err := c.cc.Invoke(ctx, RatingService_GetRatingDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) ReplyToRating(ctx context.Context, in *ReplyToRatingRequest, opts ...grpc.CallOption) (*ReplyToRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplyToRatingReply)
	err := c.cc.Invoke(ctx, RatingService_ReplyToRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRatingSummary(ctx context.Context, in *GetRatingSummaryRequest, opts ...grpc.CallOption) (*GetRatingSummaryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingSummaryReply)
	err := c.cc.Invoke(ctx, RatingService_GetRatingSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRatingList(ctx context.Context, in *GetRatingListRequest, opts ...grpc.CallOption) (*GetRatingListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingListReply)
	err := c.cc.Invoke(ctx, RatingService_GetRatingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) HideRating(ctx context.Context, in *HideRatingRequest, opts ...grpc.CallOption) (*HideRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HideRatingReply)
	err := c.cc.Invoke(ctx, RatingService_HideRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) GetRatingStatistics(ctx context.Context, in *GetRatingStatisticsRequest, opts ...grpc.CallOption) (*GetRatingStatisticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRatingStatisticsReply)
	err := c.cc.Invoke(ctx, RatingService_GetRatingStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingServiceClient) RecalculateRating(ctx context.Context, in *RecalculateRatingRequest, opts ...grpc.CallOption) (*RecalculateRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecalculateRatingReply)
	err := c.cc.Invoke(ctx, RatingService_RecalculateRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServiceServer is the server API for RatingService service.
// All implementations must embed UnimplementedRatingServiceServer
// for forward compatibility
//
// 骑手评分服务
type RatingServiceServer interface {
	// 提交评分
	SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingReply, error)
	// 获取骑手评分
	GetRiderRating(context.Context, *GetRiderRatingRequest) (*GetRiderRatingReply, error)
	// 获取评分记录列表
	GetRatingRecords(context.Context, *GetRatingRecordsRequest) (*GetRatingRecordsReply, error)
	// 获取评分详情
	GetRatingDetail(context.Context, *GetRatingDetailRequest) (*GetRatingDetailReply, error)
	// 回复评价
	ReplyToRating(context.Context, *ReplyToRatingRequest) (*ReplyToRatingReply, error)
	// 获取评分汇总
	GetRatingSummary(context.Context, *GetRatingSummaryRequest) (*GetRatingSummaryReply, error)
	// 获取评分列表
	GetRatingList(context.Context, *GetRatingListRequest) (*GetRatingListReply, error)
	// 隐藏评分
	HideRating(context.Context, *HideRatingRequest) (*HideRatingReply, error)
	// 获取评分统计
	GetRatingStatistics(context.Context, *GetRatingStatisticsRequest) (*GetRatingStatisticsReply, error)
	// 重新计算评分
	RecalculateRating(context.Context, *RecalculateRatingRequest) (*RecalculateRatingReply, error)
	mustEmbedUnimplementedRatingServiceServer()
}

// UnimplementedRatingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRatingServiceServer struct {
}

func (UnimplementedRatingServiceServer) SubmitRating(context.Context, *SubmitRatingRequest) (*SubmitRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitRating not implemented")
}
func (UnimplementedRatingServiceServer) GetRiderRating(context.Context, *GetRiderRatingRequest) (*GetRiderRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiderRating not implemented")
}
func (UnimplementedRatingServiceServer) GetRatingRecords(context.Context, *GetRatingRecordsRequest) (*GetRatingRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingRecords not implemented")
}
func (UnimplementedRatingServiceServer) GetRatingDetail(context.Context, *GetRatingDetailRequest) (*GetRatingDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingDetail not implemented")
}
func (UnimplementedRatingServiceServer) ReplyToRating(context.Context, *ReplyToRatingRequest) (*ReplyToRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplyToRating not implemented")
}
func (UnimplementedRatingServiceServer) GetRatingSummary(context.Context, *GetRatingSummaryRequest) (*GetRatingSummaryReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingSummary not implemented")
}
func (UnimplementedRatingServiceServer) GetRatingList(context.Context, *GetRatingListRequest) (*GetRatingListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingList not implemented")
}
func (UnimplementedRatingServiceServer) HideRating(context.Context, *HideRatingRequest) (*HideRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HideRating not implemented")
}
func (UnimplementedRatingServiceServer) GetRatingStatistics(context.Context, *GetRatingStatisticsRequest) (*GetRatingStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRatingStatistics not implemented")
}
func (UnimplementedRatingServiceServer) RecalculateRating(context.Context, *RecalculateRatingRequest) (*RecalculateRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecalculateRating not implemented")
}
func (UnimplementedRatingServiceServer) mustEmbedUnimplementedRatingServiceServer() {}

// UnsafeRatingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServiceServer will
// result in compilation errors.
type UnsafeRatingServiceServer interface {
	mustEmbedUnimplementedRatingServiceServer()
}

func RegisterRatingServiceServer(s grpc.ServiceRegistrar, srv RatingServiceServer) {
	s.RegisterService(&RatingService_ServiceDesc, srv)
}

func _RatingService_SubmitRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).SubmitRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_SubmitRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).SubmitRating(ctx, req.(*SubmitRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRiderRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRiderRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRiderRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRiderRating(ctx, req.(*GetRiderRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRatingRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRatingRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRatingRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRatingRecords(ctx, req.(*GetRatingRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRatingDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRatingDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRatingDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRatingDetail(ctx, req.(*GetRatingDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_ReplyToRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyToRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).ReplyToRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_ReplyToRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).ReplyToRating(ctx, req.(*ReplyToRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRatingSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRatingSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRatingSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRatingSummary(ctx, req.(*GetRatingSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRatingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRatingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRatingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRatingList(ctx, req.(*GetRatingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_HideRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HideRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).HideRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_HideRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).HideRating(ctx, req.(*HideRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_GetRatingStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRatingStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).GetRatingStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_GetRatingStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).GetRatingStatistics(ctx, req.(*GetRatingStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RatingService_RecalculateRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecalculateRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServiceServer).RecalculateRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RatingService_RecalculateRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServiceServer).RecalculateRating(ctx, req.(*RecalculateRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RatingService_ServiceDesc is the grpc.ServiceDesc for RatingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RatingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.RatingService",
	HandlerType: (*RatingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitRating",
			Handler:    _RatingService_SubmitRating_Handler,
		},
		{
			MethodName: "GetRiderRating",
			Handler:    _RatingService_GetRiderRating_Handler,
		},
		{
			MethodName: "GetRatingRecords",
			Handler:    _RatingService_GetRatingRecords_Handler,
		},
		{
			MethodName: "GetRatingDetail",
			Handler:    _RatingService_GetRatingDetail_Handler,
		},
		{
			MethodName: "ReplyToRating",
			Handler:    _RatingService_ReplyToRating_Handler,
		},
		{
			MethodName: "GetRatingSummary",
			Handler:    _RatingService_GetRatingSummary_Handler,
		},
		{
			MethodName: "GetRatingList",
			Handler:    _RatingService_GetRatingList_Handler,
		},
		{
			MethodName: "HideRating",
			Handler:    _RatingService_HideRating_Handler,
		},
		{
			MethodName: "GetRatingStatistics",
			Handler:    _RatingService_GetRatingStatistics_Handler,
		},
		{
			MethodName: "RecalculateRating",
			Handler:    _RatingService_RecalculateRating_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/rating.proto",
}
