// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: api/rider/v1/rating.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Rating_SubmitOrderRating_FullMethodName   = "/api.rider.v1.Rating/SubmitOrderRating"
	Rating_GetRiderRatings_FullMethodName     = "/api.rider.v1.Rating/GetRiderRatings"
	Rating_GetRiderRatingStats_FullMethodName = "/api.rider.v1.Rating/GetRiderRatingStats"
	Rating_SubmitComplaint_FullMethodName     = "/api.rider.v1.Rating/SubmitComplaint"
	Rating_GetComplaints_FullMethodName       = "/api.rider.v1.Rating/GetComplaints"
)

// RatingClient is the client API for Rating service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 评价服务
type RatingClient interface {
	// 提交订单评价
	SubmitOrderRating(ctx context.Context, in *SubmitOrderRatingRequest, opts ...grpc.CallOption) (*SubmitOrderRatingReply, error)
	// 获取骑手评价列表
	GetRiderRatings(ctx context.Context, in *GetRiderRatingsRequest, opts ...grpc.CallOption) (*GetRiderRatingsReply, error)
	// 获取骑手评分统计
	GetRiderRatingStats(ctx context.Context, in *GetRiderRatingStatsRequest, opts ...grpc.CallOption) (*GetRiderRatingStatsReply, error)
	// 提交投诉
	SubmitComplaint(ctx context.Context, in *SubmitComplaintRequest, opts ...grpc.CallOption) (*SubmitComplaintReply, error)
	// 获取投诉列表
	GetComplaints(ctx context.Context, in *GetComplaintsRequest, opts ...grpc.CallOption) (*GetComplaintsReply, error)
}

type ratingClient struct {
	cc grpc.ClientConnInterface
}

func NewRatingClient(cc grpc.ClientConnInterface) RatingClient {
	return &ratingClient{cc}
}

func (c *ratingClient) SubmitOrderRating(ctx context.Context, in *SubmitOrderRatingRequest, opts ...grpc.CallOption) (*SubmitOrderRatingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitOrderRatingReply)
	err := c.cc.Invoke(ctx, Rating_SubmitOrderRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetRiderRatings(ctx context.Context, in *GetRiderRatingsRequest, opts ...grpc.CallOption) (*GetRiderRatingsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderRatingsReply)
	err := c.cc.Invoke(ctx, Rating_GetRiderRatings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetRiderRatingStats(ctx context.Context, in *GetRiderRatingStatsRequest, opts ...grpc.CallOption) (*GetRiderRatingStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRiderRatingStatsReply)
	err := c.cc.Invoke(ctx, Rating_GetRiderRatingStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) SubmitComplaint(ctx context.Context, in *SubmitComplaintRequest, opts ...grpc.CallOption) (*SubmitComplaintReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitComplaintReply)
	err := c.cc.Invoke(ctx, Rating_SubmitComplaint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ratingClient) GetComplaints(ctx context.Context, in *GetComplaintsRequest, opts ...grpc.CallOption) (*GetComplaintsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetComplaintsReply)
	err := c.cc.Invoke(ctx, Rating_GetComplaints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RatingServer is the server API for Rating service.
// All implementations must embed UnimplementedRatingServer
// for forward compatibility
//
// 评价服务
type RatingServer interface {
	// 提交订单评价
	SubmitOrderRating(context.Context, *SubmitOrderRatingRequest) (*SubmitOrderRatingReply, error)
	// 获取骑手评价列表
	GetRiderRatings(context.Context, *GetRiderRatingsRequest) (*GetRiderRatingsReply, error)
	// 获取骑手评分统计
	GetRiderRatingStats(context.Context, *GetRiderRatingStatsRequest) (*GetRiderRatingStatsReply, error)
	// 提交投诉
	SubmitComplaint(context.Context, *SubmitComplaintRequest) (*SubmitComplaintReply, error)
	// 获取投诉列表
	GetComplaints(context.Context, *GetComplaintsRequest) (*GetComplaintsReply, error)
	mustEmbedUnimplementedRatingServer()
}

// UnimplementedRatingServer must be embedded to have forward compatible implementations.
type UnimplementedRatingServer struct {
}

func (UnimplementedRatingServer) SubmitOrderRating(context.Context, *SubmitOrderRatingRequest) (*SubmitOrderRatingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitOrderRating not implemented")
}
func (UnimplementedRatingServer) GetRiderRatings(context.Context, *GetRiderRatingsRequest) (*GetRiderRatingsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiderRatings not implemented")
}
func (UnimplementedRatingServer) GetRiderRatingStats(context.Context, *GetRiderRatingStatsRequest) (*GetRiderRatingStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiderRatingStats not implemented")
}
func (UnimplementedRatingServer) SubmitComplaint(context.Context, *SubmitComplaintRequest) (*SubmitComplaintReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitComplaint not implemented")
}
func (UnimplementedRatingServer) GetComplaints(context.Context, *GetComplaintsRequest) (*GetComplaintsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetComplaints not implemented")
}
func (UnimplementedRatingServer) mustEmbedUnimplementedRatingServer() {}

// UnsafeRatingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RatingServer will
// result in compilation errors.
type UnsafeRatingServer interface {
	mustEmbedUnimplementedRatingServer()
}

func RegisterRatingServer(s grpc.ServiceRegistrar, srv RatingServer) {
	s.RegisterService(&Rating_ServiceDesc, srv)
}

func _Rating_SubmitOrderRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitOrderRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).SubmitOrderRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_SubmitOrderRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).SubmitOrderRating(ctx, req.(*SubmitOrderRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetRiderRatings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderRatingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetRiderRatings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetRiderRatings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetRiderRatings(ctx, req.(*GetRiderRatingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetRiderRatingStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiderRatingStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetRiderRatingStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetRiderRatingStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetRiderRatingStats(ctx, req.(*GetRiderRatingStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_SubmitComplaint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitComplaintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).SubmitComplaint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_SubmitComplaint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).SubmitComplaint(ctx, req.(*SubmitComplaintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rating_GetComplaints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetComplaintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RatingServer).GetComplaints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rating_GetComplaints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RatingServer).GetComplaints(ctx, req.(*GetComplaintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Rating_ServiceDesc is the grpc.ServiceDesc for Rating service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rating_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Rating",
	HandlerType: (*RatingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitOrderRating",
			Handler:    _Rating_SubmitOrderRating_Handler,
		},
		{
			MethodName: "GetRiderRatings",
			Handler:    _Rating_GetRiderRatings_Handler,
		},
		{
			MethodName: "GetRiderRatingStats",
			Handler:    _Rating_GetRiderRatingStats_Handler,
		},
		{
			MethodName: "SubmitComplaint",
			Handler:    _Rating_SubmitComplaint_Handler,
		},
		{
			MethodName: "GetComplaints",
			Handler:    _Rating_GetComplaints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rider/v1/rating.proto",
}
