// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/referral.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Referral_GenerateInviteCode_FullMethodName    = "/api.rider.v1.Referral/GenerateInviteCode"
	Referral_GetMyReferralInfo_FullMethodName     = "/api.rider.v1.Referral/GetMyReferralInfo"
	Referral_GetInviteRecordList_FullMethodName   = "/api.rider.v1.Referral/GetInviteRecordList"
	Referral_ValidateInviteCode_FullMethodName    = "/api.rider.v1.Referral/ValidateInviteCode"
	Referral_BindReferralRelation_FullMethodName  = "/api.rider.v1.Referral/BindReferralRelation"
	Referral_GetTaskList_FullMethodName           = "/api.rider.v1.Referral/GetTaskList"
	Referral_GetTaskProgress_FullMethodName       = "/api.rider.v1.Referral/GetTaskProgress"
	Referral_ClaimTaskReward_FullMethodName       = "/api.rider.v1.Referral/ClaimTaskReward"
	Referral_GetRewardRecordList_FullMethodName   = "/api.rider.v1.Referral/GetRewardRecordList"
	Referral_GetReferralStatistics_FullMethodName = "/api.rider.v1.Referral/GetReferralStatistics"
)

// ReferralClient is the client API for Referral service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 骑手拉新服务
type ReferralClient interface {
	// 生成邀请码
	GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeReply, error)
	// 获取我的邀请信息
	GetMyReferralInfo(ctx context.Context, in *GetMyReferralInfoRequest, opts ...grpc.CallOption) (*GetMyReferralInfoReply, error)
	// 获取邀请记录列表
	GetInviteRecordList(ctx context.Context, in *GetInviteRecordListRequest, opts ...grpc.CallOption) (*GetInviteRecordListReply, error)
	// 验证邀请码
	ValidateInviteCode(ctx context.Context, in *ValidateInviteCodeRequest, opts ...grpc.CallOption) (*ValidateInviteCodeReply, error)
	// 绑定邀请关系（新骑手注册时调用）
	BindReferralRelation(ctx context.Context, in *BindReferralRelationRequest, opts ...grpc.CallOption) (*BindReferralRelationReply, error)
	// 获取任务列表
	GetTaskList(ctx context.Context, in *GetTaskListRequest, opts ...grpc.CallOption) (*GetTaskListReply, error)
	// 获取任务进度
	GetTaskProgress(ctx context.Context, in *GetTaskProgressRequest, opts ...grpc.CallOption) (*GetTaskProgressReply, error)
	// 领取任务奖励
	ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error)
	// 获取奖励记录
	GetRewardRecordList(ctx context.Context, in *GetRewardRecordListRequest, opts ...grpc.CallOption) (*GetRewardRecordListReply, error)
	// 获取拉新统计数据（管理后台用）
	GetReferralStatistics(ctx context.Context, in *GetReferralStatisticsRequest, opts ...grpc.CallOption) (*GetReferralStatisticsReply, error)
}

type referralClient struct {
	cc grpc.ClientConnInterface
}

func NewReferralClient(cc grpc.ClientConnInterface) ReferralClient {
	return &referralClient{cc}
}

func (c *referralClient) GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...grpc.CallOption) (*GenerateInviteCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateInviteCodeReply)
	err := c.cc.Invoke(ctx, Referral_GenerateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetMyReferralInfo(ctx context.Context, in *GetMyReferralInfoRequest, opts ...grpc.CallOption) (*GetMyReferralInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyReferralInfoReply)
	err := c.cc.Invoke(ctx, Referral_GetMyReferralInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetInviteRecordList(ctx context.Context, in *GetInviteRecordListRequest, opts ...grpc.CallOption) (*GetInviteRecordListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInviteRecordListReply)
	err := c.cc.Invoke(ctx, Referral_GetInviteRecordList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) ValidateInviteCode(ctx context.Context, in *ValidateInviteCodeRequest, opts ...grpc.CallOption) (*ValidateInviteCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateInviteCodeReply)
	err := c.cc.Invoke(ctx, Referral_ValidateInviteCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) BindReferralRelation(ctx context.Context, in *BindReferralRelationRequest, opts ...grpc.CallOption) (*BindReferralRelationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindReferralRelationReply)
	err := c.cc.Invoke(ctx, Referral_BindReferralRelation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetTaskList(ctx context.Context, in *GetTaskListRequest, opts ...grpc.CallOption) (*GetTaskListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskListReply)
	err := c.cc.Invoke(ctx, Referral_GetTaskList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetTaskProgress(ctx context.Context, in *GetTaskProgressRequest, opts ...grpc.CallOption) (*GetTaskProgressReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskProgressReply)
	err := c.cc.Invoke(ctx, Referral_GetTaskProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...grpc.CallOption) (*ClaimTaskRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimTaskRewardReply)
	err := c.cc.Invoke(ctx, Referral_ClaimTaskReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetRewardRecordList(ctx context.Context, in *GetRewardRecordListRequest, opts ...grpc.CallOption) (*GetRewardRecordListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRewardRecordListReply)
	err := c.cc.Invoke(ctx, Referral_GetRewardRecordList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *referralClient) GetReferralStatistics(ctx context.Context, in *GetReferralStatisticsRequest, opts ...grpc.CallOption) (*GetReferralStatisticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferralStatisticsReply)
	err := c.cc.Invoke(ctx, Referral_GetReferralStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReferralServer is the server API for Referral service.
// All implementations must embed UnimplementedReferralServer
// for forward compatibility
//
// 骑手拉新服务
type ReferralServer interface {
	// 生成邀请码
	GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeReply, error)
	// 获取我的邀请信息
	GetMyReferralInfo(context.Context, *GetMyReferralInfoRequest) (*GetMyReferralInfoReply, error)
	// 获取邀请记录列表
	GetInviteRecordList(context.Context, *GetInviteRecordListRequest) (*GetInviteRecordListReply, error)
	// 验证邀请码
	ValidateInviteCode(context.Context, *ValidateInviteCodeRequest) (*ValidateInviteCodeReply, error)
	// 绑定邀请关系（新骑手注册时调用）
	BindReferralRelation(context.Context, *BindReferralRelationRequest) (*BindReferralRelationReply, error)
	// 获取任务列表
	GetTaskList(context.Context, *GetTaskListRequest) (*GetTaskListReply, error)
	// 获取任务进度
	GetTaskProgress(context.Context, *GetTaskProgressRequest) (*GetTaskProgressReply, error)
	// 领取任务奖励
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error)
	// 获取奖励记录
	GetRewardRecordList(context.Context, *GetRewardRecordListRequest) (*GetRewardRecordListReply, error)
	// 获取拉新统计数据（管理后台用）
	GetReferralStatistics(context.Context, *GetReferralStatisticsRequest) (*GetReferralStatisticsReply, error)
	mustEmbedUnimplementedReferralServer()
}

// UnimplementedReferralServer must be embedded to have forward compatible implementations.
type UnimplementedReferralServer struct {
}

func (UnimplementedReferralServer) GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateInviteCode not implemented")
}
func (UnimplementedReferralServer) GetMyReferralInfo(context.Context, *GetMyReferralInfoRequest) (*GetMyReferralInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMyReferralInfo not implemented")
}
func (UnimplementedReferralServer) GetInviteRecordList(context.Context, *GetInviteRecordListRequest) (*GetInviteRecordListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInviteRecordList not implemented")
}
func (UnimplementedReferralServer) ValidateInviteCode(context.Context, *ValidateInviteCodeRequest) (*ValidateInviteCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateInviteCode not implemented")
}
func (UnimplementedReferralServer) BindReferralRelation(context.Context, *BindReferralRelationRequest) (*BindReferralRelationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindReferralRelation not implemented")
}
func (UnimplementedReferralServer) GetTaskList(context.Context, *GetTaskListRequest) (*GetTaskListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskList not implemented")
}
func (UnimplementedReferralServer) GetTaskProgress(context.Context, *GetTaskProgressRequest) (*GetTaskProgressReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskProgress not implemented")
}
func (UnimplementedReferralServer) ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTaskReward not implemented")
}
func (UnimplementedReferralServer) GetRewardRecordList(context.Context, *GetRewardRecordListRequest) (*GetRewardRecordListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRewardRecordList not implemented")
}
func (UnimplementedReferralServer) GetReferralStatistics(context.Context, *GetReferralStatisticsRequest) (*GetReferralStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReferralStatistics not implemented")
}
func (UnimplementedReferralServer) mustEmbedUnimplementedReferralServer() {}

// UnsafeReferralServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReferralServer will
// result in compilation errors.
type UnsafeReferralServer interface {
	mustEmbedUnimplementedReferralServer()
}

func RegisterReferralServer(s grpc.ServiceRegistrar, srv ReferralServer) {
	s.RegisterService(&Referral_ServiceDesc, srv)
}

func _Referral_GenerateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GenerateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GenerateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GenerateInviteCode(ctx, req.(*GenerateInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetMyReferralInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyReferralInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetMyReferralInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetMyReferralInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetMyReferralInfo(ctx, req.(*GetMyReferralInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetInviteRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteRecordListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetInviteRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetInviteRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetInviteRecordList(ctx, req.(*GetInviteRecordListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_ValidateInviteCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateInviteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).ValidateInviteCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_ValidateInviteCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).ValidateInviteCode(ctx, req.(*ValidateInviteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_BindReferralRelation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindReferralRelationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).BindReferralRelation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_BindReferralRelation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).BindReferralRelation(ctx, req.(*BindReferralRelationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetTaskList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetTaskList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetTaskList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetTaskList(ctx, req.(*GetTaskListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetTaskProgress(ctx, req.(*GetTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_ClaimTaskReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).ClaimTaskReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_ClaimTaskReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetRewardRecordList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRewardRecordListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetRewardRecordList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetRewardRecordList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetRewardRecordList(ctx, req.(*GetRewardRecordListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Referral_GetReferralStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferralStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReferralServer).GetReferralStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Referral_GetReferralStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReferralServer).GetReferralStatistics(ctx, req.(*GetReferralStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Referral_ServiceDesc is the grpc.ServiceDesc for Referral service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Referral_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Referral",
	HandlerType: (*ReferralServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateInviteCode",
			Handler:    _Referral_GenerateInviteCode_Handler,
		},
		{
			MethodName: "GetMyReferralInfo",
			Handler:    _Referral_GetMyReferralInfo_Handler,
		},
		{
			MethodName: "GetInviteRecordList",
			Handler:    _Referral_GetInviteRecordList_Handler,
		},
		{
			MethodName: "ValidateInviteCode",
			Handler:    _Referral_ValidateInviteCode_Handler,
		},
		{
			MethodName: "BindReferralRelation",
			Handler:    _Referral_BindReferralRelation_Handler,
		},
		{
			MethodName: "GetTaskList",
			Handler:    _Referral_GetTaskList_Handler,
		},
		{
			MethodName: "GetTaskProgress",
			Handler:    _Referral_GetTaskProgress_Handler,
		},
		{
			MethodName: "ClaimTaskReward",
			Handler:    _Referral_ClaimTaskReward_Handler,
		},
		{
			MethodName: "GetRewardRecordList",
			Handler:    _Referral_GetRewardRecordList_Handler,
		},
		{
			MethodName: "GetReferralStatistics",
			Handler:    _Referral_GetReferralStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/referral.proto",
}
