// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/referral.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationReferralBindReferralRelation = "/api.rider.v1.Referral/BindReferralRelation"
const OperationReferralClaimTaskReward = "/api.rider.v1.Referral/ClaimTaskReward"
const OperationReferralGenerateInviteCode = "/api.rider.v1.Referral/GenerateInviteCode"
const OperationReferralGetInviteRecordList = "/api.rider.v1.Referral/GetInviteRecordList"
const OperationReferralGetMyReferralInfo = "/api.rider.v1.Referral/GetMyReferralInfo"
const OperationReferralGetReferralStatistics = "/api.rider.v1.Referral/GetReferralStatistics"
const OperationReferralGetRewardRecordList = "/api.rider.v1.Referral/GetRewardRecordList"
const OperationReferralGetTaskList = "/api.rider.v1.Referral/GetTaskList"
const OperationReferralGetTaskProgress = "/api.rider.v1.Referral/GetTaskProgress"
const OperationReferralValidateInviteCode = "/api.rider.v1.Referral/ValidateInviteCode"

type ReferralHTTPServer interface {
	// BindReferralRelation 绑定邀请关系（新骑手注册时调用）
	BindReferralRelation(context.Context, *BindReferralRelationRequest) (*BindReferralRelationReply, error)
	// ClaimTaskReward 领取任务奖励
	ClaimTaskReward(context.Context, *ClaimTaskRewardRequest) (*ClaimTaskRewardReply, error)
	// GenerateInviteCode 生成邀请码
	GenerateInviteCode(context.Context, *GenerateInviteCodeRequest) (*GenerateInviteCodeReply, error)
	// GetInviteRecordList 获取邀请记录列表
	GetInviteRecordList(context.Context, *GetInviteRecordListRequest) (*GetInviteRecordListReply, error)
	// GetMyReferralInfo 获取我的邀请信息
	GetMyReferralInfo(context.Context, *GetMyReferralInfoRequest) (*GetMyReferralInfoReply, error)
	// GetReferralStatistics 获取拉新统计数据（管理后台用）
	GetReferralStatistics(context.Context, *GetReferralStatisticsRequest) (*GetReferralStatisticsReply, error)
	// GetRewardRecordList 获取奖励记录
	GetRewardRecordList(context.Context, *GetRewardRecordListRequest) (*GetRewardRecordListReply, error)
	// GetTaskList 获取任务列表
	GetTaskList(context.Context, *GetTaskListRequest) (*GetTaskListReply, error)
	// GetTaskProgress 获取任务进度
	GetTaskProgress(context.Context, *GetTaskProgressRequest) (*GetTaskProgressReply, error)
	// ValidateInviteCode 验证邀请码
	ValidateInviteCode(context.Context, *ValidateInviteCodeRequest) (*ValidateInviteCodeReply, error)
}

func RegisterReferralHTTPServer(s *http.Server, srv ReferralHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/referral/invite-code/generate", _Referral_GenerateInviteCode0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/my-info", _Referral_GetMyReferralInfo0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/invite-records", _Referral_GetInviteRecordList0_HTTP_Handler(srv))
	r.POST("/rider/v1/referral/invite-code/validate", _Referral_ValidateInviteCode0_HTTP_Handler(srv))
	r.POST("/rider/v1/referral/bind", _Referral_BindReferralRelation0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/tasks", _Referral_GetTaskList0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/task-progress/{task_id}", _Referral_GetTaskProgress0_HTTP_Handler(srv))
	r.POST("/rider/v1/referral/tasks/{task_id}/claim", _Referral_ClaimTaskReward0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/reward-records", _Referral_GetRewardRecordList0_HTTP_Handler(srv))
	r.GET("/rider/v1/referral/statistics", _Referral_GetReferralStatistics0_HTTP_Handler(srv))
}

func _Referral_GenerateInviteCode0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateInviteCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGenerateInviteCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateInviteCode(ctx, req.(*GenerateInviteCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateInviteCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetMyReferralInfo0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetMyReferralInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetMyReferralInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetMyReferralInfo(ctx, req.(*GetMyReferralInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetMyReferralInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetInviteRecordList0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInviteRecordListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetInviteRecordList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInviteRecordList(ctx, req.(*GetInviteRecordListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInviteRecordListReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_ValidateInviteCode0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateInviteCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralValidateInviteCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ValidateInviteCode(ctx, req.(*ValidateInviteCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateInviteCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_BindReferralRelation0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BindReferralRelationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralBindReferralRelation)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.BindReferralRelation(ctx, req.(*BindReferralRelationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BindReferralRelationReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetTaskList0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetTaskList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskList(ctx, req.(*GetTaskListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskListReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetTaskProgress0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskProgressRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetTaskProgress)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskProgress(ctx, req.(*GetTaskProgressRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskProgressReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_ClaimTaskReward0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ClaimTaskRewardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralClaimTaskReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ClaimTaskReward(ctx, req.(*ClaimTaskRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ClaimTaskRewardReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetRewardRecordList0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRewardRecordListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetRewardRecordList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRewardRecordList(ctx, req.(*GetRewardRecordListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRewardRecordListReply)
		return ctx.Result(200, reply)
	}
}

func _Referral_GetReferralStatistics0_HTTP_Handler(srv ReferralHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetReferralStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationReferralGetReferralStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReferralStatistics(ctx, req.(*GetReferralStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetReferralStatisticsReply)
		return ctx.Result(200, reply)
	}
}

type ReferralHTTPClient interface {
	// BindReferralRelation 绑定邀请关系（新骑手注册时调用）
	BindReferralRelation(ctx context.Context, req *BindReferralRelationRequest, opts ...http.CallOption) (rsp *BindReferralRelationReply, err error)
	// ClaimTaskReward 领取任务奖励
	ClaimTaskReward(ctx context.Context, req *ClaimTaskRewardRequest, opts ...http.CallOption) (rsp *ClaimTaskRewardReply, err error)
	// GenerateInviteCode 生成邀请码
	GenerateInviteCode(ctx context.Context, req *GenerateInviteCodeRequest, opts ...http.CallOption) (rsp *GenerateInviteCodeReply, err error)
	// GetInviteRecordList 获取邀请记录列表
	GetInviteRecordList(ctx context.Context, req *GetInviteRecordListRequest, opts ...http.CallOption) (rsp *GetInviteRecordListReply, err error)
	// GetMyReferralInfo 获取我的邀请信息
	GetMyReferralInfo(ctx context.Context, req *GetMyReferralInfoRequest, opts ...http.CallOption) (rsp *GetMyReferralInfoReply, err error)
	// GetReferralStatistics 获取拉新统计数据（管理后台用）
	GetReferralStatistics(ctx context.Context, req *GetReferralStatisticsRequest, opts ...http.CallOption) (rsp *GetReferralStatisticsReply, err error)
	// GetRewardRecordList 获取奖励记录
	GetRewardRecordList(ctx context.Context, req *GetRewardRecordListRequest, opts ...http.CallOption) (rsp *GetRewardRecordListReply, err error)
	// GetTaskList 获取任务列表
	GetTaskList(ctx context.Context, req *GetTaskListRequest, opts ...http.CallOption) (rsp *GetTaskListReply, err error)
	// GetTaskProgress 获取任务进度
	GetTaskProgress(ctx context.Context, req *GetTaskProgressRequest, opts ...http.CallOption) (rsp *GetTaskProgressReply, err error)
	// ValidateInviteCode 验证邀请码
	ValidateInviteCode(ctx context.Context, req *ValidateInviteCodeRequest, opts ...http.CallOption) (rsp *ValidateInviteCodeReply, err error)
}

type ReferralHTTPClientImpl struct {
	cc *http.Client
}

func NewReferralHTTPClient(client *http.Client) ReferralHTTPClient {
	return &ReferralHTTPClientImpl{client}
}

// BindReferralRelation 绑定邀请关系（新骑手注册时调用）
func (c *ReferralHTTPClientImpl) BindReferralRelation(ctx context.Context, in *BindReferralRelationRequest, opts ...http.CallOption) (*BindReferralRelationReply, error) {
	var out BindReferralRelationReply
	pattern := "/rider/v1/referral/bind"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralBindReferralRelation))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ClaimTaskReward 领取任务奖励
func (c *ReferralHTTPClientImpl) ClaimTaskReward(ctx context.Context, in *ClaimTaskRewardRequest, opts ...http.CallOption) (*ClaimTaskRewardReply, error) {
	var out ClaimTaskRewardReply
	pattern := "/rider/v1/referral/tasks/{task_id}/claim"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralClaimTaskReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GenerateInviteCode 生成邀请码
func (c *ReferralHTTPClientImpl) GenerateInviteCode(ctx context.Context, in *GenerateInviteCodeRequest, opts ...http.CallOption) (*GenerateInviteCodeReply, error) {
	var out GenerateInviteCodeReply
	pattern := "/rider/v1/referral/invite-code/generate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralGenerateInviteCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInviteRecordList 获取邀请记录列表
func (c *ReferralHTTPClientImpl) GetInviteRecordList(ctx context.Context, in *GetInviteRecordListRequest, opts ...http.CallOption) (*GetInviteRecordListReply, error) {
	var out GetInviteRecordListReply
	pattern := "/rider/v1/referral/invite-records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetInviteRecordList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetMyReferralInfo 获取我的邀请信息
func (c *ReferralHTTPClientImpl) GetMyReferralInfo(ctx context.Context, in *GetMyReferralInfoRequest, opts ...http.CallOption) (*GetMyReferralInfoReply, error) {
	var out GetMyReferralInfoReply
	pattern := "/rider/v1/referral/my-info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetMyReferralInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReferralStatistics 获取拉新统计数据（管理后台用）
func (c *ReferralHTTPClientImpl) GetReferralStatistics(ctx context.Context, in *GetReferralStatisticsRequest, opts ...http.CallOption) (*GetReferralStatisticsReply, error) {
	var out GetReferralStatisticsReply
	pattern := "/rider/v1/referral/statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetReferralStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRewardRecordList 获取奖励记录
func (c *ReferralHTTPClientImpl) GetRewardRecordList(ctx context.Context, in *GetRewardRecordListRequest, opts ...http.CallOption) (*GetRewardRecordListReply, error) {
	var out GetRewardRecordListReply
	pattern := "/rider/v1/referral/reward-records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetRewardRecordList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskList 获取任务列表
func (c *ReferralHTTPClientImpl) GetTaskList(ctx context.Context, in *GetTaskListRequest, opts ...http.CallOption) (*GetTaskListReply, error) {
	var out GetTaskListReply
	pattern := "/rider/v1/referral/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetTaskList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskProgress 获取任务进度
func (c *ReferralHTTPClientImpl) GetTaskProgress(ctx context.Context, in *GetTaskProgressRequest, opts ...http.CallOption) (*GetTaskProgressReply, error) {
	var out GetTaskProgressReply
	pattern := "/rider/v1/referral/task-progress/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationReferralGetTaskProgress))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ValidateInviteCode 验证邀请码
func (c *ReferralHTTPClientImpl) ValidateInviteCode(ctx context.Context, in *ValidateInviteCodeRequest, opts ...http.CallOption) (*ValidateInviteCodeReply, error) {
	var out ValidateInviteCodeReply
	pattern := "/rider/v1/referral/invite-code/validate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationReferralValidateInviteCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
