// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: api/rider/v1/safety.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Safety_EmergencyHelp_FullMethodName           = "/api.rider.v1.Safety/EmergencyHelp"
	Safety_CancelEmergency_FullMethodName         = "/api.rider.v1.Safety/CancelEmergency"
	Safety_GetEmergencyRecords_FullMethodName     = "/api.rider.v1.Safety/GetEmergencyRecords"
	Safety_SubmitInsuranceClaim_FullMethodName    = "/api.rider.v1.Safety/SubmitInsuranceClaim"
	Safety_GetInsuranceClaims_FullMethodName      = "/api.rider.v1.Safety/GetInsuranceClaims"
	Safety_GetInsuranceClaimDetail_FullMethodName = "/api.rider.v1.Safety/GetInsuranceClaimDetail"
	Safety_GetInsuranceInfo_FullMethodName        = "/api.rider.v1.Safety/GetInsuranceInfo"
	Safety_ReportSafetyEvent_FullMethodName       = "/api.rider.v1.Safety/ReportSafetyEvent"
	Safety_GetSafetyTips_FullMethodName           = "/api.rider.v1.Safety/GetSafetyTips"
	Safety_UpdateEmergencyContacts_FullMethodName = "/api.rider.v1.Safety/UpdateEmergencyContacts"
	Safety_GetEmergencyContacts_FullMethodName    = "/api.rider.v1.Safety/GetEmergencyContacts"
)

// SafetyClient is the client API for Safety service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 安全服务
type SafetyClient interface {
	// 发起紧急求助
	EmergencyHelp(ctx context.Context, in *EmergencyHelpRequest, opts ...grpc.CallOption) (*EmergencyHelpReply, error)
	// 取消紧急求助
	CancelEmergency(ctx context.Context, in *CancelEmergencyRequest, opts ...grpc.CallOption) (*CancelEmergencyReply, error)
	// 获取紧急求助记录
	GetEmergencyRecords(ctx context.Context, in *GetEmergencyRecordsRequest, opts ...grpc.CallOption) (*GetEmergencyRecordsReply, error)
	// 提交保险理赔申请
	SubmitInsuranceClaim(ctx context.Context, in *SubmitInsuranceClaimRequest, opts ...grpc.CallOption) (*SubmitInsuranceClaimReply, error)
	// 获取保险理赔列表
	GetInsuranceClaims(ctx context.Context, in *GetInsuranceClaimsRequest, opts ...grpc.CallOption) (*GetInsuranceClaimsReply, error)
	// 获取保险理赔详情
	GetInsuranceClaimDetail(ctx context.Context, in *GetInsuranceClaimDetailRequest, opts ...grpc.CallOption) (*GetInsuranceClaimDetailReply, error)
	// 获取保险信息
	GetInsuranceInfo(ctx context.Context, in *GetInsuranceInfoRequest, opts ...grpc.CallOption) (*GetInsuranceInfoReply, error)
	// 上报安全事件
	ReportSafetyEvent(ctx context.Context, in *ReportSafetyEventRequest, opts ...grpc.CallOption) (*ReportSafetyEventReply, error)
	// 获取安全提示
	GetSafetyTips(ctx context.Context, in *GetSafetyTipsRequest, opts ...grpc.CallOption) (*GetSafetyTipsReply, error)
	// 更新紧急联系人
	UpdateEmergencyContacts(ctx context.Context, in *UpdateEmergencyContactsRequest, opts ...grpc.CallOption) (*UpdateEmergencyContactsReply, error)
	// 获取紧急联系人
	GetEmergencyContacts(ctx context.Context, in *GetEmergencyContactsRequest, opts ...grpc.CallOption) (*GetEmergencyContactsReply, error)
}

type safetyClient struct {
	cc grpc.ClientConnInterface
}

func NewSafetyClient(cc grpc.ClientConnInterface) SafetyClient {
	return &safetyClient{cc}
}

func (c *safetyClient) EmergencyHelp(ctx context.Context, in *EmergencyHelpRequest, opts ...grpc.CallOption) (*EmergencyHelpReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmergencyHelpReply)
	err := c.cc.Invoke(ctx, Safety_EmergencyHelp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) CancelEmergency(ctx context.Context, in *CancelEmergencyRequest, opts ...grpc.CallOption) (*CancelEmergencyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelEmergencyReply)
	err := c.cc.Invoke(ctx, Safety_CancelEmergency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetEmergencyRecords(ctx context.Context, in *GetEmergencyRecordsRequest, opts ...grpc.CallOption) (*GetEmergencyRecordsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmergencyRecordsReply)
	err := c.cc.Invoke(ctx, Safety_GetEmergencyRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) SubmitInsuranceClaim(ctx context.Context, in *SubmitInsuranceClaimRequest, opts ...grpc.CallOption) (*SubmitInsuranceClaimReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitInsuranceClaimReply)
	err := c.cc.Invoke(ctx, Safety_SubmitInsuranceClaim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetInsuranceClaims(ctx context.Context, in *GetInsuranceClaimsRequest, opts ...grpc.CallOption) (*GetInsuranceClaimsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsuranceClaimsReply)
	err := c.cc.Invoke(ctx, Safety_GetInsuranceClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetInsuranceClaimDetail(ctx context.Context, in *GetInsuranceClaimDetailRequest, opts ...grpc.CallOption) (*GetInsuranceClaimDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsuranceClaimDetailReply)
	err := c.cc.Invoke(ctx, Safety_GetInsuranceClaimDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetInsuranceInfo(ctx context.Context, in *GetInsuranceInfoRequest, opts ...grpc.CallOption) (*GetInsuranceInfoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInsuranceInfoReply)
	err := c.cc.Invoke(ctx, Safety_GetInsuranceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) ReportSafetyEvent(ctx context.Context, in *ReportSafetyEventRequest, opts ...grpc.CallOption) (*ReportSafetyEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSafetyEventReply)
	err := c.cc.Invoke(ctx, Safety_ReportSafetyEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetSafetyTips(ctx context.Context, in *GetSafetyTipsRequest, opts ...grpc.CallOption) (*GetSafetyTipsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSafetyTipsReply)
	err := c.cc.Invoke(ctx, Safety_GetSafetyTips_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) UpdateEmergencyContacts(ctx context.Context, in *UpdateEmergencyContactsRequest, opts ...grpc.CallOption) (*UpdateEmergencyContactsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEmergencyContactsReply)
	err := c.cc.Invoke(ctx, Safety_UpdateEmergencyContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *safetyClient) GetEmergencyContacts(ctx context.Context, in *GetEmergencyContactsRequest, opts ...grpc.CallOption) (*GetEmergencyContactsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmergencyContactsReply)
	err := c.cc.Invoke(ctx, Safety_GetEmergencyContacts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SafetyServer is the server API for Safety service.
// All implementations must embed UnimplementedSafetyServer
// for forward compatibility
//
// 安全服务
type SafetyServer interface {
	// 发起紧急求助
	EmergencyHelp(context.Context, *EmergencyHelpRequest) (*EmergencyHelpReply, error)
	// 取消紧急求助
	CancelEmergency(context.Context, *CancelEmergencyRequest) (*CancelEmergencyReply, error)
	// 获取紧急求助记录
	GetEmergencyRecords(context.Context, *GetEmergencyRecordsRequest) (*GetEmergencyRecordsReply, error)
	// 提交保险理赔申请
	SubmitInsuranceClaim(context.Context, *SubmitInsuranceClaimRequest) (*SubmitInsuranceClaimReply, error)
	// 获取保险理赔列表
	GetInsuranceClaims(context.Context, *GetInsuranceClaimsRequest) (*GetInsuranceClaimsReply, error)
	// 获取保险理赔详情
	GetInsuranceClaimDetail(context.Context, *GetInsuranceClaimDetailRequest) (*GetInsuranceClaimDetailReply, error)
	// 获取保险信息
	GetInsuranceInfo(context.Context, *GetInsuranceInfoRequest) (*GetInsuranceInfoReply, error)
	// 上报安全事件
	ReportSafetyEvent(context.Context, *ReportSafetyEventRequest) (*ReportSafetyEventReply, error)
	// 获取安全提示
	GetSafetyTips(context.Context, *GetSafetyTipsRequest) (*GetSafetyTipsReply, error)
	// 更新紧急联系人
	UpdateEmergencyContacts(context.Context, *UpdateEmergencyContactsRequest) (*UpdateEmergencyContactsReply, error)
	// 获取紧急联系人
	GetEmergencyContacts(context.Context, *GetEmergencyContactsRequest) (*GetEmergencyContactsReply, error)
	mustEmbedUnimplementedSafetyServer()
}

// UnimplementedSafetyServer must be embedded to have forward compatible implementations.
type UnimplementedSafetyServer struct {
}

func (UnimplementedSafetyServer) EmergencyHelp(context.Context, *EmergencyHelpRequest) (*EmergencyHelpReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmergencyHelp not implemented")
}
func (UnimplementedSafetyServer) CancelEmergency(context.Context, *CancelEmergencyRequest) (*CancelEmergencyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelEmergency not implemented")
}
func (UnimplementedSafetyServer) GetEmergencyRecords(context.Context, *GetEmergencyRecordsRequest) (*GetEmergencyRecordsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmergencyRecords not implemented")
}
func (UnimplementedSafetyServer) SubmitInsuranceClaim(context.Context, *SubmitInsuranceClaimRequest) (*SubmitInsuranceClaimReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitInsuranceClaim not implemented")
}
func (UnimplementedSafetyServer) GetInsuranceClaims(context.Context, *GetInsuranceClaimsRequest) (*GetInsuranceClaimsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsuranceClaims not implemented")
}
func (UnimplementedSafetyServer) GetInsuranceClaimDetail(context.Context, *GetInsuranceClaimDetailRequest) (*GetInsuranceClaimDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsuranceClaimDetail not implemented")
}
func (UnimplementedSafetyServer) GetInsuranceInfo(context.Context, *GetInsuranceInfoRequest) (*GetInsuranceInfoReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInsuranceInfo not implemented")
}
func (UnimplementedSafetyServer) ReportSafetyEvent(context.Context, *ReportSafetyEventRequest) (*ReportSafetyEventReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSafetyEvent not implemented")
}
func (UnimplementedSafetyServer) GetSafetyTips(context.Context, *GetSafetyTipsRequest) (*GetSafetyTipsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSafetyTips not implemented")
}
func (UnimplementedSafetyServer) UpdateEmergencyContacts(context.Context, *UpdateEmergencyContactsRequest) (*UpdateEmergencyContactsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmergencyContacts not implemented")
}
func (UnimplementedSafetyServer) GetEmergencyContacts(context.Context, *GetEmergencyContactsRequest) (*GetEmergencyContactsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmergencyContacts not implemented")
}
func (UnimplementedSafetyServer) mustEmbedUnimplementedSafetyServer() {}

// UnsafeSafetyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SafetyServer will
// result in compilation errors.
type UnsafeSafetyServer interface {
	mustEmbedUnimplementedSafetyServer()
}

func RegisterSafetyServer(s grpc.ServiceRegistrar, srv SafetyServer) {
	s.RegisterService(&Safety_ServiceDesc, srv)
}

func _Safety_EmergencyHelp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmergencyHelpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).EmergencyHelp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_EmergencyHelp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).EmergencyHelp(ctx, req.(*EmergencyHelpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_CancelEmergency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelEmergencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).CancelEmergency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_CancelEmergency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).CancelEmergency(ctx, req.(*CancelEmergencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetEmergencyRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmergencyRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetEmergencyRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetEmergencyRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetEmergencyRecords(ctx, req.(*GetEmergencyRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_SubmitInsuranceClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitInsuranceClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).SubmitInsuranceClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_SubmitInsuranceClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).SubmitInsuranceClaim(ctx, req.(*SubmitInsuranceClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetInsuranceClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsuranceClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetInsuranceClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetInsuranceClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetInsuranceClaims(ctx, req.(*GetInsuranceClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetInsuranceClaimDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsuranceClaimDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetInsuranceClaimDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetInsuranceClaimDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetInsuranceClaimDetail(ctx, req.(*GetInsuranceClaimDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetInsuranceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInsuranceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetInsuranceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetInsuranceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetInsuranceInfo(ctx, req.(*GetInsuranceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_ReportSafetyEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSafetyEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).ReportSafetyEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_ReportSafetyEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).ReportSafetyEvent(ctx, req.(*ReportSafetyEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetSafetyTips_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSafetyTipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetSafetyTips(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetSafetyTips_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetSafetyTips(ctx, req.(*GetSafetyTipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_UpdateEmergencyContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEmergencyContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).UpdateEmergencyContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_UpdateEmergencyContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).UpdateEmergencyContacts(ctx, req.(*UpdateEmergencyContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Safety_GetEmergencyContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmergencyContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyServer).GetEmergencyContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Safety_GetEmergencyContacts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyServer).GetEmergencyContacts(ctx, req.(*GetEmergencyContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Safety_ServiceDesc is the grpc.ServiceDesc for Safety service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Safety_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Safety",
	HandlerType: (*SafetyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmergencyHelp",
			Handler:    _Safety_EmergencyHelp_Handler,
		},
		{
			MethodName: "CancelEmergency",
			Handler:    _Safety_CancelEmergency_Handler,
		},
		{
			MethodName: "GetEmergencyRecords",
			Handler:    _Safety_GetEmergencyRecords_Handler,
		},
		{
			MethodName: "SubmitInsuranceClaim",
			Handler:    _Safety_SubmitInsuranceClaim_Handler,
		},
		{
			MethodName: "GetInsuranceClaims",
			Handler:    _Safety_GetInsuranceClaims_Handler,
		},
		{
			MethodName: "GetInsuranceClaimDetail",
			Handler:    _Safety_GetInsuranceClaimDetail_Handler,
		},
		{
			MethodName: "GetInsuranceInfo",
			Handler:    _Safety_GetInsuranceInfo_Handler,
		},
		{
			MethodName: "ReportSafetyEvent",
			Handler:    _Safety_ReportSafetyEvent_Handler,
		},
		{
			MethodName: "GetSafetyTips",
			Handler:    _Safety_GetSafetyTips_Handler,
		},
		{
			MethodName: "UpdateEmergencyContacts",
			Handler:    _Safety_UpdateEmergencyContacts_Handler,
		},
		{
			MethodName: "GetEmergencyContacts",
			Handler:    _Safety_GetEmergencyContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rider/v1/safety.proto",
}
