// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: api/rider/v1/safety.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSafetyCancelEmergency = "/api.rider.v1.Safety/CancelEmergency"
const OperationSafetyEmergencyHelp = "/api.rider.v1.Safety/EmergencyHelp"
const OperationSafetyGetEmergencyContacts = "/api.rider.v1.Safety/GetEmergencyContacts"
const OperationSafetyGetEmergencyRecords = "/api.rider.v1.Safety/GetEmergencyRecords"
const OperationSafetyGetInsuranceClaimDetail = "/api.rider.v1.Safety/GetInsuranceClaimDetail"
const OperationSafetyGetInsuranceClaims = "/api.rider.v1.Safety/GetInsuranceClaims"
const OperationSafetyGetInsuranceInfo = "/api.rider.v1.Safety/GetInsuranceInfo"
const OperationSafetyGetSafetyTips = "/api.rider.v1.Safety/GetSafetyTips"
const OperationSafetyReportSafetyEvent = "/api.rider.v1.Safety/ReportSafetyEvent"
const OperationSafetySubmitInsuranceClaim = "/api.rider.v1.Safety/SubmitInsuranceClaim"
const OperationSafetyUpdateEmergencyContacts = "/api.rider.v1.Safety/UpdateEmergencyContacts"

type SafetyHTTPServer interface {
	// CancelEmergency 取消紧急求助
	CancelEmergency(context.Context, *CancelEmergencyRequest) (*CancelEmergencyReply, error)
	// EmergencyHelp 发起紧急求助
	EmergencyHelp(context.Context, *EmergencyHelpRequest) (*EmergencyHelpReply, error)
	// GetEmergencyContacts 获取紧急联系人
	GetEmergencyContacts(context.Context, *GetEmergencyContactsRequest) (*GetEmergencyContactsReply, error)
	// GetEmergencyRecords 获取紧急求助记录
	GetEmergencyRecords(context.Context, *GetEmergencyRecordsRequest) (*GetEmergencyRecordsReply, error)
	// GetInsuranceClaimDetail 获取保险理赔详情
	GetInsuranceClaimDetail(context.Context, *GetInsuranceClaimDetailRequest) (*GetInsuranceClaimDetailReply, error)
	// GetInsuranceClaims 获取保险理赔列表
	GetInsuranceClaims(context.Context, *GetInsuranceClaimsRequest) (*GetInsuranceClaimsReply, error)
	// GetInsuranceInfo 获取保险信息
	GetInsuranceInfo(context.Context, *GetInsuranceInfoRequest) (*GetInsuranceInfoReply, error)
	// GetSafetyTips 获取安全提示
	GetSafetyTips(context.Context, *GetSafetyTipsRequest) (*GetSafetyTipsReply, error)
	// ReportSafetyEvent 上报安全事件
	ReportSafetyEvent(context.Context, *ReportSafetyEventRequest) (*ReportSafetyEventReply, error)
	// SubmitInsuranceClaim 提交保险理赔申请
	SubmitInsuranceClaim(context.Context, *SubmitInsuranceClaimRequest) (*SubmitInsuranceClaimReply, error)
	// UpdateEmergencyContacts 更新紧急联系人
	UpdateEmergencyContacts(context.Context, *UpdateEmergencyContactsRequest) (*UpdateEmergencyContactsReply, error)
}

func RegisterSafetyHTTPServer(s *http.Server, srv SafetyHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/safety/emergency", _Safety_EmergencyHelp0_HTTP_Handler(srv))
	r.POST("/rider/v1/safety/emergency/{emergency_id}/cancel", _Safety_CancelEmergency0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/emergency/records", _Safety_GetEmergencyRecords0_HTTP_Handler(srv))
	r.POST("/rider/v1/safety/insurance/claim", _Safety_SubmitInsuranceClaim0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/insurance/claims", _Safety_GetInsuranceClaims0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/insurance/claim/{claim_id}", _Safety_GetInsuranceClaimDetail0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/insurance/info", _Safety_GetInsuranceInfo0_HTTP_Handler(srv))
	r.POST("/rider/v1/safety/event", _Safety_ReportSafetyEvent0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/tips", _Safety_GetSafetyTips0_HTTP_Handler(srv))
	r.POST("/rider/v1/safety/contacts", _Safety_UpdateEmergencyContacts0_HTTP_Handler(srv))
	r.GET("/rider/v1/safety/contacts", _Safety_GetEmergencyContacts0_HTTP_Handler(srv))
}

func _Safety_EmergencyHelp0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in EmergencyHelpRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyEmergencyHelp)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.EmergencyHelp(ctx, req.(*EmergencyHelpRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*EmergencyHelpReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_CancelEmergency0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelEmergencyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyCancelEmergency)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelEmergency(ctx, req.(*CancelEmergencyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelEmergencyReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetEmergencyRecords0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmergencyRecordsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetEmergencyRecords)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmergencyRecords(ctx, req.(*GetEmergencyRecordsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmergencyRecordsReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_SubmitInsuranceClaim0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SubmitInsuranceClaimRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetySubmitInsuranceClaim)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SubmitInsuranceClaim(ctx, req.(*SubmitInsuranceClaimRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SubmitInsuranceClaimReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetInsuranceClaims0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInsuranceClaimsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetInsuranceClaims)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInsuranceClaims(ctx, req.(*GetInsuranceClaimsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInsuranceClaimsReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetInsuranceClaimDetail0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInsuranceClaimDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetInsuranceClaimDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInsuranceClaimDetail(ctx, req.(*GetInsuranceClaimDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInsuranceClaimDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetInsuranceInfo0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetInsuranceInfoRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetInsuranceInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetInsuranceInfo(ctx, req.(*GetInsuranceInfoRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetInsuranceInfoReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_ReportSafetyEvent0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReportSafetyEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyReportSafetyEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReportSafetyEvent(ctx, req.(*ReportSafetyEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReportSafetyEventReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetSafetyTips0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetSafetyTipsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetSafetyTips)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetSafetyTips(ctx, req.(*GetSafetyTipsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetSafetyTipsReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_UpdateEmergencyContacts0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateEmergencyContactsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyUpdateEmergencyContacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateEmergencyContacts(ctx, req.(*UpdateEmergencyContactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateEmergencyContactsReply)
		return ctx.Result(200, reply)
	}
}

func _Safety_GetEmergencyContacts0_HTTP_Handler(srv SafetyHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetEmergencyContactsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSafetyGetEmergencyContacts)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetEmergencyContacts(ctx, req.(*GetEmergencyContactsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetEmergencyContactsReply)
		return ctx.Result(200, reply)
	}
}

type SafetyHTTPClient interface {
	// CancelEmergency 取消紧急求助
	CancelEmergency(ctx context.Context, req *CancelEmergencyRequest, opts ...http.CallOption) (rsp *CancelEmergencyReply, err error)
	// EmergencyHelp 发起紧急求助
	EmergencyHelp(ctx context.Context, req *EmergencyHelpRequest, opts ...http.CallOption) (rsp *EmergencyHelpReply, err error)
	// GetEmergencyContacts 获取紧急联系人
	GetEmergencyContacts(ctx context.Context, req *GetEmergencyContactsRequest, opts ...http.CallOption) (rsp *GetEmergencyContactsReply, err error)
	// GetEmergencyRecords 获取紧急求助记录
	GetEmergencyRecords(ctx context.Context, req *GetEmergencyRecordsRequest, opts ...http.CallOption) (rsp *GetEmergencyRecordsReply, err error)
	// GetInsuranceClaimDetail 获取保险理赔详情
	GetInsuranceClaimDetail(ctx context.Context, req *GetInsuranceClaimDetailRequest, opts ...http.CallOption) (rsp *GetInsuranceClaimDetailReply, err error)
	// GetInsuranceClaims 获取保险理赔列表
	GetInsuranceClaims(ctx context.Context, req *GetInsuranceClaimsRequest, opts ...http.CallOption) (rsp *GetInsuranceClaimsReply, err error)
	// GetInsuranceInfo 获取保险信息
	GetInsuranceInfo(ctx context.Context, req *GetInsuranceInfoRequest, opts ...http.CallOption) (rsp *GetInsuranceInfoReply, err error)
	// GetSafetyTips 获取安全提示
	GetSafetyTips(ctx context.Context, req *GetSafetyTipsRequest, opts ...http.CallOption) (rsp *GetSafetyTipsReply, err error)
	// ReportSafetyEvent 上报安全事件
	ReportSafetyEvent(ctx context.Context, req *ReportSafetyEventRequest, opts ...http.CallOption) (rsp *ReportSafetyEventReply, err error)
	// SubmitInsuranceClaim 提交保险理赔申请
	SubmitInsuranceClaim(ctx context.Context, req *SubmitInsuranceClaimRequest, opts ...http.CallOption) (rsp *SubmitInsuranceClaimReply, err error)
	// UpdateEmergencyContacts 更新紧急联系人
	UpdateEmergencyContacts(ctx context.Context, req *UpdateEmergencyContactsRequest, opts ...http.CallOption) (rsp *UpdateEmergencyContactsReply, err error)
}

type SafetyHTTPClientImpl struct {
	cc *http.Client
}

func NewSafetyHTTPClient(client *http.Client) SafetyHTTPClient {
	return &SafetyHTTPClientImpl{client}
}

// CancelEmergency 取消紧急求助
func (c *SafetyHTTPClientImpl) CancelEmergency(ctx context.Context, in *CancelEmergencyRequest, opts ...http.CallOption) (*CancelEmergencyReply, error) {
	var out CancelEmergencyReply
	pattern := "/rider/v1/safety/emergency/{emergency_id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSafetyCancelEmergency))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// EmergencyHelp 发起紧急求助
func (c *SafetyHTTPClientImpl) EmergencyHelp(ctx context.Context, in *EmergencyHelpRequest, opts ...http.CallOption) (*EmergencyHelpReply, error) {
	var out EmergencyHelpReply
	pattern := "/rider/v1/safety/emergency"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSafetyEmergencyHelp))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEmergencyContacts 获取紧急联系人
func (c *SafetyHTTPClientImpl) GetEmergencyContacts(ctx context.Context, in *GetEmergencyContactsRequest, opts ...http.CallOption) (*GetEmergencyContactsReply, error) {
	var out GetEmergencyContactsReply
	pattern := "/rider/v1/safety/contacts"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetEmergencyContacts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetEmergencyRecords 获取紧急求助记录
func (c *SafetyHTTPClientImpl) GetEmergencyRecords(ctx context.Context, in *GetEmergencyRecordsRequest, opts ...http.CallOption) (*GetEmergencyRecordsReply, error) {
	var out GetEmergencyRecordsReply
	pattern := "/rider/v1/safety/emergency/records"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetEmergencyRecords))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInsuranceClaimDetail 获取保险理赔详情
func (c *SafetyHTTPClientImpl) GetInsuranceClaimDetail(ctx context.Context, in *GetInsuranceClaimDetailRequest, opts ...http.CallOption) (*GetInsuranceClaimDetailReply, error) {
	var out GetInsuranceClaimDetailReply
	pattern := "/rider/v1/safety/insurance/claim/{claim_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetInsuranceClaimDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInsuranceClaims 获取保险理赔列表
func (c *SafetyHTTPClientImpl) GetInsuranceClaims(ctx context.Context, in *GetInsuranceClaimsRequest, opts ...http.CallOption) (*GetInsuranceClaimsReply, error) {
	var out GetInsuranceClaimsReply
	pattern := "/rider/v1/safety/insurance/claims"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetInsuranceClaims))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetInsuranceInfo 获取保险信息
func (c *SafetyHTTPClientImpl) GetInsuranceInfo(ctx context.Context, in *GetInsuranceInfoRequest, opts ...http.CallOption) (*GetInsuranceInfoReply, error) {
	var out GetInsuranceInfoReply
	pattern := "/rider/v1/safety/insurance/info"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetInsuranceInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetSafetyTips 获取安全提示
func (c *SafetyHTTPClientImpl) GetSafetyTips(ctx context.Context, in *GetSafetyTipsRequest, opts ...http.CallOption) (*GetSafetyTipsReply, error) {
	var out GetSafetyTipsReply
	pattern := "/rider/v1/safety/tips"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSafetyGetSafetyTips))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReportSafetyEvent 上报安全事件
func (c *SafetyHTTPClientImpl) ReportSafetyEvent(ctx context.Context, in *ReportSafetyEventRequest, opts ...http.CallOption) (*ReportSafetyEventReply, error) {
	var out ReportSafetyEventReply
	pattern := "/rider/v1/safety/event"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSafetyReportSafetyEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// SubmitInsuranceClaim 提交保险理赔申请
func (c *SafetyHTTPClientImpl) SubmitInsuranceClaim(ctx context.Context, in *SubmitInsuranceClaimRequest, opts ...http.CallOption) (*SubmitInsuranceClaimReply, error) {
	var out SubmitInsuranceClaimReply
	pattern := "/rider/v1/safety/insurance/claim"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSafetySubmitInsuranceClaim))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateEmergencyContacts 更新紧急联系人
func (c *SafetyHTTPClientImpl) UpdateEmergencyContacts(ctx context.Context, in *UpdateEmergencyContactsRequest, opts ...http.CallOption) (*UpdateEmergencyContactsReply, error) {
	var out UpdateEmergencyContactsReply
	pattern := "/rider/v1/safety/contacts"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationSafetyUpdateEmergencyContacts))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
