// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v3.19.4
// source: rider/v1/ticket.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTicketAddTicketReply = "/api.rider.v1.Ticket/AddTicketReply"
const OperationTicketCreateTicket = "/api.rider.v1.Ticket/CreateTicket"
const OperationTicketGetTicketDetail = "/api.rider.v1.Ticket/GetTicketDetail"
const OperationTicketGetTicketList = "/api.rider.v1.Ticket/GetTicketList"
const OperationTicketGetTicketStatistics = "/api.rider.v1.Ticket/GetTicketStatistics"
const OperationTicketUpdateTicketStatus = "/api.rider.v1.Ticket/UpdateTicketStatus"

type TicketHTTPServer interface {
	// AddTicketReply 添加工单回复
	AddTicketReply(context.Context, *AddTicketReplyRequest) (*AddTicketReplyReply, error)
	// CreateTicket 创建工单
	CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketReply, error)
	// GetTicketDetail 获取工单详情
	GetTicketDetail(context.Context, *GetTicketDetailRequest) (*GetTicketDetailReply, error)
	// GetTicketList 获取工单列表
	GetTicketList(context.Context, *GetTicketListRequest) (*GetTicketListReply, error)
	// GetTicketStatistics 获取工单统计
	GetTicketStatistics(context.Context, *GetTicketStatisticsRequest) (*GetTicketStatisticsReply, error)
	// UpdateTicketStatus 更新工单状态
	UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*UpdateTicketStatusReply, error)
}

func RegisterTicketHTTPServer(s *http.Server, srv TicketHTTPServer) {
	r := s.Route("/")
	r.POST("/rider/v1/ticket/create", _Ticket_CreateTicket0_HTTP_Handler(srv))
	r.GET("/rider/v1/tickets", _Ticket_GetTicketList0_HTTP_Handler(srv))
	r.GET("/rider/v1/ticket/{ticket_id}", _Ticket_GetTicketDetail0_HTTP_Handler(srv))
	r.POST("/rider/v1/ticket/reply", _Ticket_AddTicketReply0_HTTP_Handler(srv))
	r.POST("/rider/v1/ticket/status", _Ticket_UpdateTicketStatus0_HTTP_Handler(srv))
	r.GET("/rider/v1/ticket/statistics", _Ticket_GetTicketStatistics0_HTTP_Handler(srv))
}

func _Ticket_CreateTicket0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTicketRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketCreateTicket)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTicket(ctx, req.(*CreateTicketRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTicketReply)
		return ctx.Result(200, reply)
	}
}

func _Ticket_GetTicketList0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTicketListRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketGetTicketList)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTicketList(ctx, req.(*GetTicketListRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTicketListReply)
		return ctx.Result(200, reply)
	}
}

func _Ticket_GetTicketDetail0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTicketDetailRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketGetTicketDetail)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTicketDetail(ctx, req.(*GetTicketDetailRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTicketDetailReply)
		return ctx.Result(200, reply)
	}
}

func _Ticket_AddTicketReply0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddTicketReplyRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketAddTicketReply)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddTicketReply(ctx, req.(*AddTicketReplyRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddTicketReplyReply)
		return ctx.Result(200, reply)
	}
}

func _Ticket_UpdateTicketStatus0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTicketStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketUpdateTicketStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTicketStatus(ctx, req.(*UpdateTicketStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTicketStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Ticket_GetTicketStatistics0_HTTP_Handler(srv TicketHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTicketStatisticsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTicketGetTicketStatistics)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTicketStatistics(ctx, req.(*GetTicketStatisticsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTicketStatisticsReply)
		return ctx.Result(200, reply)
	}
}

type TicketHTTPClient interface {
	// AddTicketReply 添加工单回复
	AddTicketReply(ctx context.Context, req *AddTicketReplyRequest, opts ...http.CallOption) (rsp *AddTicketReplyReply, err error)
	// CreateTicket 创建工单
	CreateTicket(ctx context.Context, req *CreateTicketRequest, opts ...http.CallOption) (rsp *CreateTicketReply, err error)
	// GetTicketDetail 获取工单详情
	GetTicketDetail(ctx context.Context, req *GetTicketDetailRequest, opts ...http.CallOption) (rsp *GetTicketDetailReply, err error)
	// GetTicketList 获取工单列表
	GetTicketList(ctx context.Context, req *GetTicketListRequest, opts ...http.CallOption) (rsp *GetTicketListReply, err error)
	// GetTicketStatistics 获取工单统计
	GetTicketStatistics(ctx context.Context, req *GetTicketStatisticsRequest, opts ...http.CallOption) (rsp *GetTicketStatisticsReply, err error)
	// UpdateTicketStatus 更新工单状态
	UpdateTicketStatus(ctx context.Context, req *UpdateTicketStatusRequest, opts ...http.CallOption) (rsp *UpdateTicketStatusReply, err error)
}

type TicketHTTPClientImpl struct {
	cc *http.Client
}

func NewTicketHTTPClient(client *http.Client) TicketHTTPClient {
	return &TicketHTTPClientImpl{client}
}

// AddTicketReply 添加工单回复
func (c *TicketHTTPClientImpl) AddTicketReply(ctx context.Context, in *AddTicketReplyRequest, opts ...http.CallOption) (*AddTicketReplyReply, error) {
	var out AddTicketReplyReply
	pattern := "/rider/v1/ticket/reply"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketAddTicketReply))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTicket 创建工单
func (c *TicketHTTPClientImpl) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...http.CallOption) (*CreateTicketReply, error) {
	var out CreateTicketReply
	pattern := "/rider/v1/ticket/create"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketCreateTicket))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTicketDetail 获取工单详情
func (c *TicketHTTPClientImpl) GetTicketDetail(ctx context.Context, in *GetTicketDetailRequest, opts ...http.CallOption) (*GetTicketDetailReply, error) {
	var out GetTicketDetailReply
	pattern := "/rider/v1/ticket/{ticket_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketGetTicketDetail))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTicketList 获取工单列表
func (c *TicketHTTPClientImpl) GetTicketList(ctx context.Context, in *GetTicketListRequest, opts ...http.CallOption) (*GetTicketListReply, error) {
	var out GetTicketListReply
	pattern := "/rider/v1/tickets"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketGetTicketList))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTicketStatistics 获取工单统计
func (c *TicketHTTPClientImpl) GetTicketStatistics(ctx context.Context, in *GetTicketStatisticsRequest, opts ...http.CallOption) (*GetTicketStatisticsReply, error) {
	var out GetTicketStatisticsReply
	pattern := "/rider/v1/ticket/statistics"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTicketGetTicketStatistics))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTicketStatus 更新工单状态
func (c *TicketHTTPClientImpl) UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...http.CallOption) (*UpdateTicketStatusReply, error) {
	var out UpdateTicketStatusReply
	pattern := "/rider/v1/ticket/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationTicketUpdateTicketStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
