// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: rider/v1/ticket.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	Ticket_CreateTicket_FullMethodName        = "/api.rider.v1.Ticket/CreateTicket"
	Ticket_GetTicketList_FullMethodName       = "/api.rider.v1.Ticket/GetTicketList"
	Ticket_GetTicketDetail_FullMethodName     = "/api.rider.v1.Ticket/GetTicketDetail"
	Ticket_AddTicketReply_FullMethodName      = "/api.rider.v1.Ticket/AddTicketReply"
	Ticket_UpdateTicketStatus_FullMethodName  = "/api.rider.v1.Ticket/UpdateTicketStatus"
	Ticket_GetTicketStatistics_FullMethodName = "/api.rider.v1.Ticket/GetTicketStatistics"
)

// TicketClient is the client API for Ticket service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 工单服务
type TicketClient interface {
	// 创建工单
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketReply, error)
	// 获取工单列表
	GetTicketList(ctx context.Context, in *GetTicketListRequest, opts ...grpc.CallOption) (*GetTicketListReply, error)
	// 获取工单详情
	GetTicketDetail(ctx context.Context, in *GetTicketDetailRequest, opts ...grpc.CallOption) (*GetTicketDetailReply, error)
	// 添加工单回复
	AddTicketReply(ctx context.Context, in *AddTicketReplyRequest, opts ...grpc.CallOption) (*AddTicketReplyReply, error)
	// 更新工单状态
	UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*UpdateTicketStatusReply, error)
	// 获取工单统计
	GetTicketStatistics(ctx context.Context, in *GetTicketStatisticsRequest, opts ...grpc.CallOption) (*GetTicketStatisticsReply, error)
}

type ticketClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketClient(cc grpc.ClientConnInterface) TicketClient {
	return &ticketClient{cc}
}

func (c *ticketClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTicketReply)
	err := c.cc.Invoke(ctx, Ticket_CreateTicket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) GetTicketList(ctx context.Context, in *GetTicketListRequest, opts ...grpc.CallOption) (*GetTicketListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketListReply)
	err := c.cc.Invoke(ctx, Ticket_GetTicketList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) GetTicketDetail(ctx context.Context, in *GetTicketDetailRequest, opts ...grpc.CallOption) (*GetTicketDetailReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketDetailReply)
	err := c.cc.Invoke(ctx, Ticket_GetTicketDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) AddTicketReply(ctx context.Context, in *AddTicketReplyRequest, opts ...grpc.CallOption) (*AddTicketReplyReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTicketReplyReply)
	err := c.cc.Invoke(ctx, Ticket_AddTicketReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) UpdateTicketStatus(ctx context.Context, in *UpdateTicketStatusRequest, opts ...grpc.CallOption) (*UpdateTicketStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTicketStatusReply)
	err := c.cc.Invoke(ctx, Ticket_UpdateTicketStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketClient) GetTicketStatistics(ctx context.Context, in *GetTicketStatisticsRequest, opts ...grpc.CallOption) (*GetTicketStatisticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTicketStatisticsReply)
	err := c.cc.Invoke(ctx, Ticket_GetTicketStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServer is the server API for Ticket service.
// All implementations must embed UnimplementedTicketServer
// for forward compatibility
//
// 工单服务
type TicketServer interface {
	// 创建工单
	CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketReply, error)
	// 获取工单列表
	GetTicketList(context.Context, *GetTicketListRequest) (*GetTicketListReply, error)
	// 获取工单详情
	GetTicketDetail(context.Context, *GetTicketDetailRequest) (*GetTicketDetailReply, error)
	// 添加工单回复
	AddTicketReply(context.Context, *AddTicketReplyRequest) (*AddTicketReplyReply, error)
	// 更新工单状态
	UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*UpdateTicketStatusReply, error)
	// 获取工单统计
	GetTicketStatistics(context.Context, *GetTicketStatisticsRequest) (*GetTicketStatisticsReply, error)
	mustEmbedUnimplementedTicketServer()
}

// UnimplementedTicketServer must be embedded to have forward compatible implementations.
type UnimplementedTicketServer struct {
}

func (UnimplementedTicketServer) CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedTicketServer) GetTicketList(context.Context, *GetTicketListRequest) (*GetTicketListReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicketList not implemented")
}
func (UnimplementedTicketServer) GetTicketDetail(context.Context, *GetTicketDetailRequest) (*GetTicketDetailReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicketDetail not implemented")
}
func (UnimplementedTicketServer) AddTicketReply(context.Context, *AddTicketReplyRequest) (*AddTicketReplyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTicketReply not implemented")
}
func (UnimplementedTicketServer) UpdateTicketStatus(context.Context, *UpdateTicketStatusRequest) (*UpdateTicketStatusReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTicketStatus not implemented")
}
func (UnimplementedTicketServer) GetTicketStatistics(context.Context, *GetTicketStatisticsRequest) (*GetTicketStatisticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicketStatistics not implemented")
}
func (UnimplementedTicketServer) mustEmbedUnimplementedTicketServer() {}

// UnsafeTicketServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServer will
// result in compilation errors.
type UnsafeTicketServer interface {
	mustEmbedUnimplementedTicketServer()
}

func RegisterTicketServer(s grpc.ServiceRegistrar, srv TicketServer) {
	s.RegisterService(&Ticket_ServiceDesc, srv)
}

func _Ticket_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_GetTicketList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).GetTicketList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_GetTicketList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).GetTicketList(ctx, req.(*GetTicketListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_GetTicketDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).GetTicketDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_GetTicketDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).GetTicketDetail(ctx, req.(*GetTicketDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_AddTicketReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTicketReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).AddTicketReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_AddTicketReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).AddTicketReply(ctx, req.(*AddTicketReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_UpdateTicketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).UpdateTicketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_UpdateTicketStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).UpdateTicketStatus(ctx, req.(*UpdateTicketStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ticket_GetTicketStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServer).GetTicketStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ticket_GetTicketStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServer).GetTicketStatistics(ctx, req.(*GetTicketStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ticket_ServiceDesc is the grpc.ServiceDesc for Ticket service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ticket_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.rider.v1.Ticket",
	HandlerType: (*TicketServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTicket",
			Handler:    _Ticket_CreateTicket_Handler,
		},
		{
			MethodName: "GetTicketList",
			Handler:    _Ticket_GetTicketList_Handler,
		},
		{
			MethodName: "GetTicketDetail",
			Handler:    _Ticket_GetTicketDetail_Handler,
		},
		{
			MethodName: "AddTicketReply",
			Handler:    _Ticket_AddTicketReply_Handler,
		},
		{
			MethodName: "UpdateTicketStatus",
			Handler:    _Ticket_UpdateTicketStatus_Handler,
		},
		{
			MethodName: "GetTicketStatistics",
			Handler:    _Ticket_GetTicketStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rider/v1/ticket.proto",
}
